### ISSUE TITLE
Indentation of `#! format: off` and `#! format: on` are not preserved

### ISSUE THREAD

**Issue by tkf** [domluna/JuliaFormatter.jl#104]
MWE:

```julia
julia> print(format_text("""
       begin
           #! format: off
           don't
               format
                   this
           #! format: on
       end
       """))
begin
#! format: off
    don't
        format
            this
        #! format: on
end
```

I see that it was mentioned in the README that

> Note the formatter expects `#! format: on` and `#! format: off` to be on its own line and the whitespace to be an exact match.

Is it related to the behavior I'm seeing?  Or is it just a bug?

Checked with v0.1.19

**Comment by domluna** [comment]
Bug

**Comment by domluna** [comment]
@tkf A regex is being used to to match `#! format: on` and off so it shouldn't need to be an exact match anymore. Probably what's going on here is similar-ish to what was going on with #102.

**Comment by tkf** [comment]
Thanks, good to know you have an idea of what's going on.

**Comment by tkf** [comment]
Wow, super fast fix! Thanks a lot.
