### ISSUE TITLE
Should we add spaces after `,` in type parameters?

### ISSUE THREAD

**Issue by singularitti** [domluna/JuliaFormatter.jl#108]
This is an edge case of formatting but I think it involves consistency:
```julia
uisng StaticArrays: Size

julia> format_text("_det(::Size{(1,1)}, x::StaticMatrix) = x[1,1]")
"_det(::Size{(1, 1)}, x::StaticMatrix) = x[1, 1]"
```
or
```julia
julia> format_text("NamedTuple{(:a,:b,:c)}([1, 2, 3])")
"NamedTuple{(:a, :b, :c)}([1, 2, 3])"
```
As you can see, `format_text` adds spaces after `,` in `{(1,1)}` and `{(:a,:b,:c)}`. Should we keep the spaces, or remove them, as we usually do on multiple type parameters?

**Comment by domluna** [comment]
No spaces only occur directly inside {} or Foo{}. I think in a case like this, spaces make sense imo.

**Comment by singularitti** [comment]
It seems that Julia itself follows this style:
```julia
julia> (a=1, b=2)
(a = 1, b = 2)

julia> typeof(ans)
NamedTuple{(:a, :b),Tuple{Int64,Int64}}
```
So I could close this issue.
