### ISSUE TITLE
Balance line breaks across the CST nodes??

### ISSUE THREAD

**Issue by haberdashPI** [domluna/JuliaFormatter.jl#112]
Here is an example of something that seems to be formatted poorly:

```julia
    weights = Dict((file, i) => w for (file, subject) in subjects for (
        i,
        w,
    ) in enumerate(weightfn.(eachrow(subject.events))))
```
Manually, I would format this as:

```julia
    weights = Dict((file, i) => w 
        for (file, subject) in subjects 
        for (i, w) in enumerate(weightfn.(eachrow(subject.events))))
```

It is much easier to read the second form (at least for me). Not knowing anything about the internals here, I'm not sure what the specific rule is that I'd like, but it seems like it should be express-able in terms of the depth of the CST at which line breaks occur. The first (actual) result is pretty asymmetric in terms of where along the CST the line break occurs, and it seems like you would want to favor line breaks that balance the nodes of the tree across lines.

**Comment by haberdashPI** [comment]
Another, much simpler rule, for this specific case, would be to favor breaking comprehensions at the start of each `for` keyword.

**Comment by domluna** [comment]
This is a case I haven't looked at a whole lot so I'm not surprised this does not format the best it could. 
 I'll take a look.
