### ISSUE TITLE
Inconsistent indentation in comprehensions

### ISSUE THREAD

**Issue by haberdashPI** [domluna/JuliaFormatter.jl#114]
Hi, thanks for rapid response to my last issue; much appreciated! It looks like things are not completely working yet:

```julia
conditions = Dict((
                sid = sid,
                label = label,
                condition = condition,
                target = target,
            ) => @λ(
                _row.condition == cond_label[condition] &&
                ((label == "correct") == _row.correct) &&
                sid == _row.sid &&
                speakers[_row.sound_index] == tindex[target] ?
                target_window[_row.sound_index] : no_indices
            )
            for condition in keys(cond_label)
            for target in keys(tindex)
        for label in ["correct", "incorrect"]
    for sid in sidfor.(eeg_files))
```

I would not have expected the `for` comprehensions at the end to have different indentations; seems like they should all be at the same indentation.

**Comment by domluna** [comment]
this is a good test case thanks @haberdashPI. I'll try to put a fix in for this shortly

**Comment by domluna** [comment]
The generators are consistently indented now but this is actually a pretty weird input and it could be formatted better so I'm cool keeping this open.

**Comment by haberdashPI** [comment]
Interesting, mostly out of curiosity, I'm wondering what the rule is in this case that leads the second two comprehensions being indented differently.

**Comment by domluna** [comment]
It's essentially due to the way lazy ops are parsed

```julia
julia> CSTParser.parse("a && b && c && d")
BinaryOpCall  16(16)
 a  2(1)
 OP: LAZY_AND  3(2)
 BinaryOpCall  11(11)
  b  2(1)
  OP: LAZY_AND  3(2)
  BinaryOpCall  6(6)
   c  2(1)
   OP: LAZY_AND  3(2)
   d  1(1)


julia> CSTParser.parse("a & b & c & d")
BinaryOpCall  13(13)
 BinaryOpCall  10(9)
  BinaryOpCall  6(5)
   a  2(1)
   OP: AND  2(1)
   b  2(1)
  OP: AND  2(1)
  c  2(1)
 OP: AND  2(1)
 d  1(1)


julia> CSTParser.parse("a + b + c + d")
ChainOpCall  13(13)
 a  2(1)
 OP: PLUS  2(1)
 b  2(1)
 OP: PLUS  2(1)
 c  2(1)
 OP: PLUS  2(1)
 d  1(1)
```

converting it to the structure of ChainOpCall should fix it.

For the code you posted specifically it looks odd because the latter && is aligned to the initial arg. So in the simple case I posted it would be equivalent to `d` being aligned with `c`. The conditional op aligned to when the expression begins `_row.condition...` which is why everything after `?` is aligned to there.

**Comment by domluna** [comment]
This now formats to 

```julia
conditions = Dict(
    (
        sid = sid,
        label = label,
        condition = condition,
        target = target,
    ) => @λ(
        _row.condition == cond_label[condition] && (
            (label == "correct") == _row.correct
        ) && sid == _row.sid && speakers[_row.sound_index] == tindex[target] ?
            target_window[_row.sound_index] : no_indices
    )
    for condition in keys(cond_label)
    for target in keys(tindex)
    for label in ["correct", "incorrect"]
    for sid in sidfor.(eeg_files)
)
```

with margin = 92, and indent = 4 so gonna close this now. I think we should the initial ( alongside Dict( but that's separate from the original context of this issue anyway.
