### ISSUE TITLE
Clarifying end of condition in `if` blocks?

### ISSUE THREAD

**Issue by tkf** [domluna/JuliaFormatter.jl#117]
I think it would be nice if formatted `if` block separates the condition part and the body part clearly, as in the input code in the example below:

```julia
julia> """
       if (
           aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ||
           aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ||
           aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
       )
           nothing
       end
       """ |> format_text |> print
if (aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ||
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ||
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)
    nothing
end
```

Just as a source of inspiration, [`black`](https://github.com/psf/black)'s output is:

```python
if (
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    or aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    or aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
):
    pass
```

They explained the reasoning behind this in their README:

> You might have noticed that closing brackets are always dedented and that a trailing comma is always added. Such formatting produces smaller diffs; when you add or remove an element, it's always just one line. Also, having the closing bracket dedented provides a clear delimiter between two distinct sections of the code that otherwise share the same indentation level (like the arguments list and the docstring in the example above).

I think this argument makes sense.  In fact, it was the basis of my argument on "empty line before `for`/`let` body rule" in #95.

Now that JuliaFormatter.jl cares more about the difference in "code sections" of `for` and `let`, would it make sense to follow a similar principle in `if` and `elseif`?

**Comment by domluna** [comment]
this is a good idea

**Comment by domluna** [comment]
@tkf #120 does what you describe if it's over the margin, which seems to be the case where it's most beneficial.

**Comment by tkf** [comment]
> #120 does what you describe if it's over the margin, which seems to be the case where it's most beneficial.

Thanks a lot! I played with it and it's really nice. I agree that it makes sense to do this only when the code would be too wide otherwise.
