### ISSUE TITLE
line breaks in indexing

### ISSUE THREAD

**Issue by mlubin** [domluna/JuliaFormatter.jl#123]
I found this surprising:
```julia
print(JuliaFormatter.format_text("some_matrix_with_a_very_long_name = another_matrix_long_name[long_index_set1, long_index_set2]", margin=80))
some_matrix_with_a_very_long_name = another_matrix_long_name[
    long_index_set1,
    long_index_set2,
]
```
Previously the code had been formatted as:
```julia
some_matrix_with_a_very_long_name =
    another_matrix_long_name[long_index_set1, long_index_set2]
```
Another option if you look at Python formatters (https://yapf.now.sh/) is:
```julia
some_matrix_with_a_very_long_name = another_matrix_long_name[
    long_name_index_set1, long_name_index_set2]
```

**Comment by domluna** [comment]
@mlubin I don't think the code was ever formatted that way (unless it was part of a function definition). I've added more types to nesting on the assignment. Maybe just allow any assignment op to nest? I'm making a PR for this rn.

**Comment by mlubin** [comment]
Thanks for the quick response!

Sorry, I wasn't clear. I meant that I had previously hand-formatted the code as:
```julia
some_matrix_with_a_very_long_name =
    another_matrix_long_name[long_index_set1, long_index_set2]
```
