### ISSUE TITLE
line break around assignment

### ISSUE THREAD

**Issue by mlubin** [domluna/JuliaFormatter.jl#124]
```julia
print(JuliaFormatter.format_text("long_name = a_very_long_name", margin=25))
long_name = a_very_long_name
```
This violates the margins. I expected:
```julia
long_name =
    a_very_long_name
```
(I don't actually use 25-character margins, this is a simplified example.)

**Comment by domluna** [comment]
It won't nest on an identifier.

https://github.com/domluna/JuliaFormatter.jl/blob/master/src/pretty.jl#L1249-L1250 is where this is determined.

**Comment by mlubin** [comment]
> It won't nest on an identifier.

What's the motivation? (I'm guessing there's an edge case?)

For this particular example, the line break is valid and produces code that respects the margins. On the other hand, [YAPF](https://yapf.now.sh/) doesn't break the line in Python.

**Comment by domluna** [comment]
I'm making it so it breaks on any assignment except if the RHS is a string. I don't think there's any benefit in that case.
