### ISSUE TITLE
Comments are not aligned to named arguments

### ISSUE THREAD

**Issue by tkf** [domluna/JuliaFormatter.jl#127]
In the example below, the indentation level of the comment is unchanged while the surrounding indent are changed:

```julia
julia> """
       (
           # hello
           a = 1, b = 2, c = 3,
       )
       """ |> format_text |> print
(
    # hello
 a = 1,
 b = 2,
 c = 3,
)
```

Wouldn't it be nice to align the comment to the surrounding like this?

```julia
(
 # hello
 a = 1,
 b = 2,
 c = 3,
)
```

Checked with:

```
(v1.3) pkg> st -m JuliaFormatter
Status `~/.julia/environments/v1.3/Manifest.toml`
  [00ebfdb7] CSTParser v1.0.0
  [98e50ef6] JuliaFormatter v0.1.30
  [0796e94c] Tokenize v0.5.6
  [8dfed614] Test
```

**Comment by domluna** [comment]
I had it do this waaaaay back and there some edge cases where it didn't format it quite right off by 1 indent and it was annoying so it removed it. That being said I think it may be worth revisiting, for all I know the bug that caused that is fixed now.

**Comment by domluna** [comment]
@tkf I have this working on https://github.com/domluna/JuliaFormatter.jl/pull/149. Could you take it for a spin, see if you can find bugs :)

**Comment by tkf** [comment]
Thanks a lot for implementing this!  I just tried #149 with a few examples and it works very well.  I'll be using this branch and I'll report bugs if I find any.

**Comment by domluna** [comment]
@tkf has there been anything you've found besides #152? which occurs on master.

**Comment by tkf** [comment]
#149 has been working very well for me.
