### ISSUE TITLE
Suggestion: always use multiple-of-`indent` indentation levels?

### ISSUE THREAD

**Issue by tkf** [domluna/JuliaFormatter.jl#128]
Currently, JuliaFormatter.jl uses indentation levels that are not multiple of four (or whatever `indent` is) in some cases.  Is there strong philosophy/opinion behind this choice?  If not, why not always restrict the indentation levels to multiple of four?  I think it has some benefits:

* As indentation level becomes less dependent on surrounding code, it produces less diff after editting code.
* Structure of nested data literals is clearer.

OTOH, if I were to guess, the benefit of current approach is that it saves width of the code and makes less line breaks.

### Example: named tuple

Consider that you have LISPy `return`-less function definition:

```julia
f(x) =
    if x
        (
         aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = 1,
         bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = 2,
         cccccccccccccccccccccccccccccccccccccccc = 3,
        )
    else
        nothing
    end
```

You may want to change to function with explicit `return` later.  However, it would introduce a large diff because the indentation of the named tuple would be changed:

```julia
function f(x)
    x = something(x, false)
    if x
        return (
            aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = 1,
            bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = 2,
            cccccccccccccccccccccccccccccccccccccccc = 3,
        )
    else
        return nothing
    end
end
```

This can be avoided by using multiple-of-four indentation level:

```julia
f(x) =
    if x
        (
            aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = 1,
            bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = 2,
            cccccccccccccccccccccccccccccccccccccccc = 3,
        )
    else
        nothing
    end
```

### Example: `using`

Currently, explicit imports with many names produces indentation based on the name of the module:

```julia
using .Some.Internal.Module: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
                             bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb,
                             cccccccccccccccccccccccccccccccccccccccc
```

This also produces a large diff when the module name is changed (e.g., `.Some.Internal.Module` -> `.Internal.Module`).

This can be avoided by using multiple-of-four indentation level:

```julia
using .Some.Internal.Module:
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb,
    cccccccccccccccccccccccccccccccccccccccc
```

### Example: Nested data structure

Consider some nested data written using literals:

```julia
[
 (
  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = 1,
  bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = 2,
  cccccccccccccccccccccccccccccccccccccccc = (
      dddddddddddddddddddddddddddddddddddddddd = 3,
      eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee = 4,
  ),
 ),
 (
  ffffffffffffffffffffffffffffffffffffffff,
  (
   gggggggggggggggggggggggggggggggggggggggg,
   hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh,
   iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii,
  ),
 ),
 jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj,
]
```

Personally I find that it is hard to grasp nested level and it is not very satisfactory that nested level of `d...` and `g...` are inconsistent.  With multiple-of-four indentation levels, I think it would make the nested structure clearer:

```julia
[
    (
        aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = 1,
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = 2,
        cccccccccccccccccccccccccccccccccccccccc = (
            dddddddddddddddddddddddddddddddddddddddd = 3,
            eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee = 4,
        ),
    ),
    (
        ffffffffffffffffffffffffffffffffffffffff,
        (
            gggggggggggggggggggggggggggggggggggggggg,
            hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh,
            iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii,
        ),
    ),
    jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj,
]
```

**Comment by domluna** [comment]
The main reason it's done the current way is so that the args never go past the offset of the opener. I was concerned it would look off so I forced everything to align to not go past the opener offset. It only occurs in a few cases anyway so it's sort of an edge case.

You make a solid argument w.r.t git diffs and having the indentation be consistent is better for readability. The last example you gave looks much better. I think the only cases where it might look worse is with a very large indentation (10) which isn't practical and not worth pandering to. By the looks other formatters don't make this attempt either.

This makes the implementation simpler as well so I'm sold.

**Comment by tkf** [comment]
Thanks a lot for reconsidering this. It's good to know that it will make implementation simpler.

> By the looks other formatters don't make this attempt either.

Yes, `black` and `gofmt` both use consistent indentation levels and they seem to work quite well.

**Comment by tkf** [comment]
Thanks for implementing this super quickly!  But I just noticed that v0.1.31 still doesn't indent `using`, `import` and `export` using multiple-of-`indent` levels.  Are you planning to change it too?

**Comment by domluna** [comment]
@tkf oops yeah I forgot about those. I'll do them next.

**Comment by tkf** [comment]
I also noticed a similar situation with macro:

```julia
@f something *
   very_very_very_very_very_very_very_very_very_very_very_very_long_expr == something

@some_long_macro_name something *
                      very_very_very_very_very_very_very_very_very_long_expr == something
```

It would be nice if the second line uses `indent` for both cases.
