### ISSUE TITLE
Whitespace for parametric type definitions

### ISSUE THREAD

**Issue by kdheepak** [domluna/JuliaFormatter.jl#140]
Some parametric type definitions are hard to read without white space between parameters.

For example, in the following code, it can be very useful to have spaces after a `,` in `Union` types.

```julia
const SparseVectorUnion{T} = Union{SparseVector{T}, SparseColumnView{T}}
const AdjOrTransSparseVectorUnion{T} = LinearAlgebra.AdjOrTrans{T, <:SparseVectorUnion{T}}
```

The above gets formatted to the following:

```julia
const SparseVectorUnion{T} = Union{SparseVector{T},SparseColumnView{T}}
const AdjOrTransSparseVectorUnion{T} = LinearAlgebra.AdjOrTrans{T,<:SparseVectorUnion{T}}
```

which in my opinion makes it harder to read.

This is tangentially related, but `julia`'s `show` functionality uses slightly inconsistent spacing for `UnionAll` types and parts of the language.

For example, here is the REPL representation of the some types and the `typeof` value of some expressions:

```julia
julia> MyUnionType = Union{X,T} where T where X
Union{X, T} where T where X

julia> MyUnionType{Int}
Union{Int64, T} where T

julia> typeof(MyUnionType{Int})
UnionAll

julia> Array{Int}
Array{Int64,N} where N

julia> typeof(Array{Int})
UnionAll

julia> typeof(Union{Nothing, Vector{Vector{Int}}})
Union

julia> NamedTuple{(:min, :max), Tuple{Int, Int}}
NamedTuple{(:min, :max),Tuple{Int64,Int64}}

julia> typeof(Tuple)
DataType

julia> typeof(NamedTuple)
UnionAll

julia> typeof((:min, :max))
Tuple{Symbol,Symbol}

julia> Val{(:min, :max)}
Val{(:min, :max)}

julia> typeof(Val{(:min, :max)})
DataType

julia> struct Parametric{X,Y,Z} end

julia> Parametric{Union{Int,Float64}, Vector{Int}, Matrix{Int}}
Parametric{Union{Float64, Int64},Array{Int64,1},Array{Int64,2}}

julia> Parametric{Union{Int,T} where T<:Number, Vector{Int}}
Parametric{Union{Int64, T} where T<:Number,Array{Int64,1},Z} where Z
```

I think this is why in Julia code bases there are several instances of spaces after commas that are quite inconsistent.

**Options**

Option 1)

Don't change the spacing after `,` in types and leave it as it is, assuming the user needs to format it a certain way for _reasons_ (readability, internal consistency, logic, etc). This will result in inconsistent code styles across various packages using `JuliaFormatter.jl`.

Option 2)

If it looks like a parametric type, always remove the space after `,`. This will decrease readability in some cases but is a simple rule to follow and understand. It will also result in a few types' `repr` being different from how they are written in code.

Option 3)

If it looks like a parametric type, always add a space after `,`. This will increase readability in some cases, but will result in a lot of types' `repr` being different from how they are written in code.

Option 4)

Follow Julia's rules for spacing for parameterized types. This means special casing `NamedTuple`, `Val`, and `Union` types. This may or may not include submitting a PR to Julia to request consistency.

**Comment by domluna** [comment]
I don't think it's a good idea to model the formatted output after the Julia REPL output. I'm also not keen to allowing spacing for certain types and not for others, especially since the most practical way of doing this would be just look at the name, i.e. `Val`, `NamedTuple`, etc.

Most (if not all) of the previous style guides opted for no spaces in type parameters so I stole that from there. 

The most reasonable thing would be to add an option which add spaces in type parameters and make it opt-in. However, would like to know if that's something folks actually really want or if it's no a big deal and no spaces are fine. The vast majority of Julia code I've encountered opts for no spaces.

**Comment by kdheepak** [comment]
Thanks for the quick comment. I was curious so I did a very quick and dirty grep search on the julia source to see if one style is preferred:

```
$ rg '[^\w]Union\{\w+?, [\w, ]+?\}' --count | wc -l
     153

$ rg '[^\w]Union\{[\w,]+?\}' --count | wc -l
     151
```

There's 153 `Union` types with at least one space and 151 `Union` types with no spaces. This search result goes through documentation (which contains REPL output) as well source, so results may be different if one does a more rigorous investigation.

**Comment by domluna** [comment]
#146 add an options for whitespaces in typedefs
