### ISSUE TITLE
@doc results in signature on same line as docstring

### ISSUE THREAD

**Issue by sethaxen** [domluna/JuliaFormatter.jl#157]
When using the `@doc` macro for docstrings, the function signature gets put on the same line as the end of the string. e.g.

```julia
julia> format_text("""
       @doc doc\"\"\"
           foo()
       \"\"\"
       foo() = bar()
       """) |> println
@doc doc"""
    foo()
""" foo() = bar()
```

If I don't use `@doc`, then this doesn't happen.

```julia
julia> format_text("""
       \"\"\"
           foo()
       \"\"\"
       foo() = bar()
       """) |> println
"""
    foo()
"""
foo() = bar()
```

**Comment by domluna** [comment]
@sethaxen Fixed on master, gonna try to close out another issue and then I'll tag a new release.

**Comment by sethaxen** [comment]
Thanks for the quick fix!
