### ISSUE TITLE
Block inside iterator/array comprehension

### ISSUE THREAD

**Issue by tkf** [domluna/JuliaFormatter.jl#170]
Currently, iterator/array comprehension with a block at the "mapping" part is formatted like this

```julia
ys = (if p1(x)
    f1(x)
elseif p2(x)
    f2(x)
else
    f3(x)
end for x in xs)
```

I think this is suboptimal since the indentation of `elseif` etc. does not reflect the scope.  It'd be nice if the output is something like this:

```julia
ys = (
    if p1(x)
        f1(x)
    elseif p2(x)
        f2(x)
    else
        f3(x)
    end for x in xs
)
```

This indentation level is consistent with the similar code written with `do` notation:

```julia
ys = map(xs) do x
    if p1(x)
        f1(x)
    elseif p2(x)
        f2(x)
    else
        f3(x)
    end
end
```

**Comment by domluna** [comment]
makes sense
