### ISSUE TITLE
detecting manually aligned code

### ISSUE THREAD

**Issue by StefanKarpinski** [domluna/JuliaFormatter.jl#179]
One of my only hangups about using JuliaFormatter universally at this point is that there is occasionally code where I want to manually line things up and autoformatting can mess with this. Here's an example I just ran JuliaFormatter on (the rest of the results look great!):
```diff
 function SuffixArray(s::S) where {S<:AbstractString}
     n = length(s)
-    index = zeros(n <= typemax(Int8)  ? Int8  :
-                  n <= typemax(Int16) ? Int16 :
-                  n <= typemax(Int32) ? Int32 : Int64, n)
+    index = zeros(
+        n <= typemax(Int8) ? Int8 :
+            n <= typemax(Int16) ? Int16 : n <= typemax(Int32) ? Int32 : Int64,
+        n,
+    )
     return SuffixArray(s, n, index)
 end
```
The manually aligned before version is much more legible to me. In pondering what to do about this, I have a few trains of thought that I just want to put out there from least to most fancy:

1. Turn formatting off for blocks like this using `#! format: off` and `#! format: on`.
2. Detect that adjacent lines have an unusual amount of syntactic similarity and automatically turn formatting off.
3. Figure out how to align things like this automatically so that they line up on adjacent lines.

We can already do 1, so that's good. I had considered 3 before but it just seems too smart to actually be implemented reliably. On the other hand 2 seems pretty doable with some clever heuristics. There might even be a 2+ variation that detects syntactic similarity modulo whitespace differences and can even adjust whitespace so that things line up better. My guess is that when things line up it's generally the punctuation that lines up while names, literals and whitespace vary.

**Comment by waldyrious** [comment]
The ternary construct is always a tricky one for code formatters. While I see the appeal of detecting and preserving manual formatting, I find it closer to these tools' philosophy to apply a consistent rule throughout. I can see two ways to do that.

One way would be to wrap the rightmost side of ternary operators in parenthesis and breaking them into a new line if they're too long. The least disruptive result (assuming a 92-char line length) would be:

```jl
index = zeros(
  n <= typemax(Int8) ? Int8 : (
    n <= typemax(Int16) ? Int16 : n <= typemax(Int32) ? Int32 : Int64
  ),
  n
)
```

...while a full-on application could possibly make the code structure more intuitive:

```jl
index = zeros(
  n <= typemax(Int8) ? Int8 : (
    n <= typemax(Int16) ? Int16 : (
      n <= typemax(Int32) ? Int32 : Int64
    )
  ),
  n
)
```

Another choice could be to do as Prettier does, which is to place the `?` and `:` in their own lines, if the full expression doesn't fit in a line. So we'd have, with minimal line breaks:

```jl
index = zeros(
  n <= typemax(Int8)
    ? Int8
    : n <= typemax(Int16) ? Int16 : n <= typemax(Int32) ? Int32 : Int64,
  n
)
```

...or, with universal application of the rule (which, again, I find more readable):

```jl
index = zeros(
  n <= typemax(Int8)
    ? Int8
    : n <= typemax(Int16)
      ? Int16
      : n <= typemax(Int32)
        ? Int32
        : Int64,
  n
)
```

A third option would be to do as Prettier, but only break the `:` part into a new line. This has the advantage of associating each condition to its value. First the minimal approach, keeping a single line where possible:

```jl
index = zeros(
  n <= typemax(Int8) ? Int8
    : n <= typemax(Int16) ? Int16 : n <= typemax(Int32) ? Int32 : Int64,
  n
)
```

...and the "same-everywhere" one:

```jl
index = zeros(
  n <= typemax(Int8) ? Int8
    : n <= typemax(Int16) ? Int16
      : n <= typemax(Int32) ? Int32
        : Int64,
  n
)
```

IMO any of these approaches (the second variant of each, that is) would be preferable to attempt to identify and preserve manual formatting. It may be worth testing them in more varied codebases, though, to ensure they don't break in pathological cases.

**Comment by StefanKarpinski** [comment]
While the example I gave happened to be of the ternary operator, the issue isn't meant to be about the ternary operator specifically, and there are many other cases where manual alignment occurs, where multiple lines have the same syntactic structure, which is made clearer by aligning them. Even something as simple as this:
```jl
const UTF8PROC_STABLE    = (1<<1)
const UTF8PROC_COMPAT    = (1<<2)
const UTF8PROC_COMPOSE   = (1<<3)
const UTF8PROC_DECOMPOSE = (1<<4)
const UTF8PROC_IGNORE    = (1<<5)
const UTF8PROC_REJECTNA  = (1<<6)
const UTF8PROC_NLF2LS    = (1<<7)
const UTF8PROC_NLF2PS    = (1<<8)
const UTF8PROC_NLF2LF    = (UTF8PROC_NLF2LS | UTF8PROC_NLF2PS)
const UTF8PROC_STRIPCC   = (1<<9)
const UTF8PROC_CASEFOLD  = (1<<10)
const UTF8PROC_CHARBOUND = (1<<11)
const UTF8PROC_LUMP      = (1<<12)
const UTF8PROC_STRIPMARK = (1<<13)
```
which gets reformatted to
```jl
const UTF8PROC_STABLE = (1 << 1)
const UTF8PROC_COMPAT = (1 << 2)
const UTF8PROC_COMPOSE = (1 << 3)
const UTF8PROC_DECOMPOSE = (1 << 4)
const UTF8PROC_IGNORE = (1 << 5)
const UTF8PROC_REJECTNA = (1 << 6)
const UTF8PROC_NLF2LS = (1 << 7)
const UTF8PROC_NLF2PS = (1 << 8)
const UTF8PROC_NLF2LF = (UTF8PROC_NLF2LS | UTF8PROC_NLF2PS)
const UTF8PROC_STRIPCC = (1 << 9)
const UTF8PROC_CASEFOLD = (1 << 10)
const UTF8PROC_CHARBOUND = (1 << 11)
const UTF8PROC_LUMP = (1 << 12)
const UTF8PROC_STRIPMARK = (1 << 13)
```
Is the formatted version unreadable? Certainly not. But it's more immediately clear what's going on with the manually aligned version. The nirvana state would be if formatter detected the intention of manual alignment and helped out by making it consistent.

**Comment by StefanKarpinski** [comment]
Here's another example:
```jl
vcat(X::T...) where {T}         = T[ X[i] for i=1:length(X) ]
vcat(X::T...) where {T<:Number} = T[ X[i] for i=1:length(X) ]
hcat(X::T...) where {T}         = T[ X[j] for i=1:1, j=1:length(X) ]
hcat(X::T...) where {T<:Number} = T[ X[j] for i=1:1, j=1:length(X) ]
```
versus
```jl
vcat(X::T...) where {T} = T[X[i] for i = 1:length(X)]
vcat(X::T...) where {T<:Number} = T[X[i] for i = 1:length(X)]
hcat(X::T...) where {T} = T[X[j] for i = 1:1, j = 1:length(X)]
hcat(X::T...) where {T<:Number} = T[X[j] for i = 1:1, j = 1:length(X)]
```

**Comment by StefanKarpinski** [comment]
Another option would be to manually mark regions to be aligned (like 1 above) but then proactively try to preserve the alignment within those regions. I.e. something like this:
```jl
#! format: align
vcat(X::T...) where {T}         = T[ X[i] for i=1:length(X) ]
vcat(X::T...) where {T<:Number} = T[ X[i] for i=1:length(X) ]
hcat(X::T...) where {T}         = T[ X[j] for i=1:1, j=1:length(X) ]
hcat(X::T...) where {T<:Number} = T[ X[j] for i=1:1, j=1:length(X) ]
#! format: on
```
In the middle, the formatter could adjust spacing to get lines to line up as much as possible.

**Comment by domluna** [comment]
What happens if a line exceeds the margin in this case?

**Comment by StefanKarpinski** [comment]
No idea! Maybe ignore line length and don't wrap in such a context?

**Comment by domluna** [comment]
> No idea! Maybe ignore line length and don't wrap in such a context?

that would work. I think, well at least for the top-level examples you gave this could be implemented fairly easily. The heuristic being if there's empty newline in between assignment binary ops then adjust the whitespace to the position of most right `=`.

**Comment by tkf** [comment]
Isn't it difficult to identify how to align the code in general?  Would it be easier if the user can specify the operator at which the lines are aligned?

```julia
#! format: align                v
vcat(X::T...) where {T}         = T[ X[i] for i=1:length(X) ]
vcat(X::T...) where {T<:Number} = T[ X[i] for i=1:length(X) ]
hcat(X::T...) where {T}         = T[ X[j] for i=1:1, j=1:length(X) ]
hcat(X::T...) where {T<:Number} = T[ X[j] for i=1:1, j=1:length(X) ]
#! format: on

#! format: align                  v       v
index = zeros(n <= typemax(Int8)  ? Int8  :
              n <= typemax(Int16) ? Int16 :
              n <= typemax(Int32) ? Int32 : Int64, n)
#! format: on
```

**Comment by StefanKarpinski** [comment]
That's a cool idea! Does the character on the first line after the comment have to match up?

**Comment by tkf** [comment]
I imagine it'd be better to throw an error if the marker `v` does not hit a token. So this would be an error:

```julia
#! format: align       v
vcat(X::T...) where {T} = T[ X[i] for i=1:length(X) ]
```

**Comment by StefanKarpinski** [comment]
But one of the points of having an autoformatter is that you should be able to do search-and-replace operations on code without thinking about it and then just run the autoformatter afterwards and have everything be nicely formatted. That's one of the reasons `go fmt` has been so useful to the Go community—it lets them do mechanical code transformations really easily: just do the transformation without worrying how ugly the output is and clean it up with `go fmt` afterwards. Requiring the code to match the alignment line would make that kind of workflow fail hard.

**Comment by tkf** [comment]
Right, that's a good point. Actually, I think detecting the token to be aligned is not hard. You just need to find out tokens that are preceded by "unusual" amount of spaces.  By "unusual", I mean

* If it is not the first token of the line, preceded by two or more spaces means "unusual."
* If it is the first token of the line, it's "unusual" if it is more than the spaces that would be used for the normal indentation algorithm. (Or maybe just ban aligning the first token?)

**Comment by domluna** [comment]
Go is the only formatter I've used that does something like this, but only in certain circumstances, which seems like the most reasonable way to go about this; base it on simple heuristics. For example, in Go, if you have variable or constant definitions at the package level it will align `=` for all binary ops that aren't separated by a newline.

```go
var (
	longVariableName = 20
	name             = 10

	anotherName = 30
)
```

We could do the same thing for const and function definitions at the top level. I think this would be the  best place to start. If it works well, then we can explore doing it in some other places.

**Comment by tkf** [comment]
You mean with `#! format: align`? Or without? It looks like gofmt needs `var (...)`; e.g., it does not align

```go
var longVariableName = 20
var name = 10
var anotherName = 30
```

So maybe `var (...)` is equivalent to `#! format: align` as suggested here?

**Comment by domluna** [comment]
without it

**Comment by baggepinnen** [comment]
It might be worth considering how this kind of comments
```julia
#! format: align                v
```
interact with tools such as Literate.jl and Weave.jl etc.
I guess those tools can be made aware of the syntax and handle it properly. 

A few thoughts, the syntax `#! format: align` is rather verbose and putting a lot of those comments in the file could easily make it ugly. I often align only on `=` in assignments, something that could be specified once at the top of the file, rather than everywhere in the code. In #227, I made the following suggestions, that can be up for discussion

Maybe alignment could work only within "blocks" that are demarcated by an empty line, so that
```julia
a = 1
bc = 2

long_variable = 1
other_var = 2
```
would align on `=` to the following
```julia
a  = 1
bc = 2

long_variable = 1
other_var     = 2
```
There would probably also have to be a "maximum LHS length", so that all left hand sides exceeding this length are ignored for alignment. That I want alignment on `=` on assignments is perhaps not obvious and not everybody is interested in that, but it could be specified in the beginning of the file with a syntax similar to what's suggested in this issue, e.g.:
```julia
#! format file: align '='
```
I'll close #227 in favor of this issue.

**Comment by baggepinnen** [comment]
> 2\. Detect that adjacent lines have an unusual amount of syntactic similarity and automatically turn formatting off.

I like this proposal, together with the detection of "unusual" amount of whitespace. If the unusual whitespace is detected, and a suitable string distance between this line and any of the adjacent lines would be increased by applying the formatting, this would be an indication that manual alignment has been applied.

I'm not sure yet how this would work over multiple lines, but the "demarcation of blocks by newline" could help limit the number of statements the search is performed over.

**Comment by vtjeng** [comment]
For people testing fixes, here's another example where the formatter undoes some manual formatting that helps with reading the input matrix:

```diff
        @testset "conv2d with (1, 1) padding, input width != input_height, stride = 1" begin
            expected_output_2d = [
-                18  30  36  42  48  34;
-                45  72  81  90  99  69;
-                81  126 135 144 153 105;
-                117 180 189 198 207 141;
-                90  138 144 150 156 106;
+                18 30 36 42 48 34
+                45 72 81 90 99 69
+                81 126 135 144 153 105
+                117 180 189 198 207 141
+                90 138 144 150 156 106
            ]
```


https://github.com/vtjeng/MIPVerify.jl/pull/49/files#diff-2c30731b2ea2931fab8b970b786c5907L468-R473

I intentionally chose _not_ to turn formatting off for blocks like this using `#! format: off` and `#! format: on`; I'm taking the slight reduction in readability as I wanted to make sure that any other formatting options would be applied in the block.

**Comment by domluna** [comment]
There's a draft PR up which implements a solution to this.

**Comment by vtjeng** [comment]
@domluna, did you find that detecting manually aligned matrices heuristically couldn't be done consistently?

**Comment by domluna** [comment]
> @domluna, did you find that detecting manually aligned matrices heuristically couldn't be done consistently?

No it should be fine, it's on my TODO list. The tree structure is different than the other examples though and I didn't want to hold up the other ones just for that.
