### ISSUE TITLE
Block inside typed array comprehension etc.

### ISSUE THREAD

**Issue by tkf** [domluna/JuliaFormatter.jl#181]
This is the output of JuliaFormatter v0.3.1

```julia
y1 = Any[if true
    very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_long_expr
end for i in 1:1]

y2 = [
    if true
        very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_long_expr
    end
    for i in 1:1
]

y3 = [if true
    short_expr
end for i in 1:1]
```

I think `y1` is incompatible with `y2`.

Also, as I argued in #170, I think it'd be nice to format `y3` like `y2`.

**Comment by domluna** [comment]
Didn't mean to entirely close this. The first example now formats like the 2nd and in the 3rd `for i in 1:1`  currently stays on the same line as `end`. This may change but right now I don't see it as a big deal.

**Comment by tkf** [comment]
Thanks for the quick fix!

```julia
y1 = Any[
    if true
        very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_long_expr
    end
    for i in 1:1
]

y2 = [
    if true
        very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_long_expr
    end
    for i in 1:1
]

y3 = [
    if true
        short_expr
    end for i in 1:1
]
```

Yeah, the last example is much better than the previous version (although, ideally, it'd be nice if tweaking the code block does not change the formatting of the next line).

**Comment by domluna** [comment]
>  (although, ideally, it'd be nice if tweaking the code block does not change the formatting of the next line).

What do you mean ?

**Comment by tkf** [comment]
I mean editing `short_expr` in `y3` to a long expression would lead to a formatting like `y2`.  It would introduce a diff at the line `end for i in 1:1`.  But as you said, it's not a severe problem compared to the one you already solved.
