### ISSUE TITLE
discussion: configuration file

### ISSUE THREAD

**Issue by aviatesk** [domluna/JuliaFormatter.jl#184]
What do you think about a configuration file, that specifies formatting options (and possibly custom styles), like [`.prettierrc` for Prettier](https://prettier.io/docs/en/configuration.html) ?

For remote formatting task, we already can use GitHub actions and thus the same configurations is used within a project.
But AFAIU, in order to share those configurations for local formatting task, we currently don't have any good way other than each project member specifies them by themselves.
If we have a configuration file, (that may or not locate at the root of project directory) JuliaFormatter.jl itself or certain frontends like Juno can respect the configuration if exist, and then all the project member can easily share the same configuration even for local formatting.

**Comment by StefanKarpinski** [comment]
Might I suggest that the format of the config file be TOML? Perhaps `.JuliaFormat.toml`?

**Comment by aviatesk** [comment]
TOML will be Julian-friendly, I think.

**Comment by aviatesk** [comment]
Yeah, I think TOML will be Julian-friendly.
Perhaps we can even reuse `Project.toml` just adding JuliaFormatter configurations like:
> Project.toml
```toml
...

[JuliaFormatterConfig]
always_for_in = true

...
```

**Comment by domluna** [comment]
a config file makes sense. I'd welcome a PR. 

I suppose you would check for the config file and overwrite the current options with those present. You'd have to do this for `format_text`, `format_file`, and `format` functions

**Comment by aviatesk** [comment]
Do you think it is more natural that we try to find a config file and respect the settings in JuliaFormatter.jl itself ?
Otherwise we can just document about config file here and leave the actual task to the frontends like Juno or julia-format.

**Comment by StefanKarpinski** [comment]
IMO it makes much more sense to leave the configuration as an argument to those functions and then make the `bin/format.jl` tool config-file aware so that it looks for a config file in the code that it's formatting and uses the config when doing the formatting by default. I don't think it makes sense to put the configuration in the project file because it's the code that's being formatted that should have the say about the config, not the code that's invoking `JuliaFormatter`. It might make sense for `.JuliaFormat.toml` files to implicitly apply to anything in or below the directory where they appear.

**Comment by domluna** [comment]
Referencing what I suggested above, thinking about it a little more, you would only have to alter `format`. I don't think it makes sense for the other functions to think about a configuration file. If it's done this way then `format` would check for a config file in the directory it's called on or the directory of the file (if a single file is the argument). Another option is to do what Stefan suggests have this be part of `bin/format.jl`.

**Comment by aviatesk** [comment]
okay I will work on this.

So as for `bin/format.jl` vs. `format`, I actually don't have a strong opinion. I _feel_ the logic to find a config file is better to live in `format` since it will cover both cases anyway. I dunno.

What I really want to make clear is how/where to write configs (my initial motivation is just to establish a discipline of how to write a configurations so that we no longer need to keep track of each config rule by patching like [this](https://github.com/JunoLab/atom-julia-client/pull/719)). @StefanKarpinski  suggested `.JuliaFormatter.toml` and now I think that way would be better. It's really possible that we want to format on code that doesn't live in a project but still we also want to have a formatter config (e.g. when scripting etc).

**Comment by aviatesk** [comment]
The basic logic has been implemented in #221
