### ISSUE TITLE
Integrate the formatter from PrettyPrinting.jl

### ISSUE THREAD

**Issue by kskyten** [domluna/JuliaFormatter.jl#186]
[PrettyPrinting.jl](https://github.com/rbt-lang/PrettyPrinting.jl) has implemented the formatting algorithm from this paper: [A New Approach to Optimal Code Formatting](https://research.google/pubs/pub44667/) for formatting composite data structures. Seems like it would be a good fit for JuliaFormatter.

**Comment by domluna** [comment]
Looks neat, thanks for the reference. I'm not sure how this would be integrated but it might be useful for specialized cases. I don't see an obvious advantage over what's already implemented though.
