### ISSUE TITLE
Integrate with editors

### ISSUE THREAD

**Issue by domluna** [domluna/JuliaFormatter.jl#19]
This is a meta-issue.

I'm going to try to get it working with my vim setup first but I think downstream editors:

https://github.com/JunoLab/Juno.jl
https://github.com/julia-vscode/julia-vscode

should be able to add it as a dependency and just use `format_file` ?

cc @pfitzseb, @davidanthoff 

no pressure 😄

**Comment by pfitzseb** [comment]
I'll integrate this as soon as it's registered :) Would be cool if you could address the feedback on https://github.com/JuliaRegistries/General/pull/2261.

**Comment by davidanthoff** [comment]
I have to admit I lost track of things here. VS Code uses https://github.com/julia-vscode/DocumentFormat.jl for code formatting, is there a reason that we now have a different package here?

Also CCing @ZacLN because he is much more familiar with what is going on in that space :)

**Comment by domluna** [comment]
@davidanthoff This is a more opinionated formatter that's width-sensitive. It started as a PR for DocumentFormat.jl at one point but it's gone through a few iterations and been in a state of flux until very recently.

**Comment by davidanthoff** [comment]
I don’t see the VS Code extension supporting two different code format packages. I would _love_ to see an option in DocumentFormat.jl for the width type formatting in this package, but I think that functionality would have to be integrated into the existing stuff we have (or to say it another way, from the VS Code extension’s point of view the original approach of a PR to DocumentFormat.jl was the right strategy to integrate this into the extension).

This is especially important given that all of this needs to live within the LS and be integrated with that. One important goal there is to eventually support all three LSP format requests (doc, range and on type).

**Comment by domluna** [comment]
@pfitzseb registered as `JuliaFormatter`

**Comment by davidanthoff** [comment]
@domluna, just out of curiosity, was there a specific reason to fork things and not contribute to DocumentFormat.jl?

**Comment by domluna** [comment]
@davidanthoff Originally I did plan to contribute these changes back into `DocumentFormat.jl` but I felt the PR was getting a little out of hand and could develop it better as a separate repo. Also, while they both format Julia code, they do things very differently, and I don't think merging it would have been straightforward.

**Comment by domluna** [comment]
@davidanthoff I think you could already do range formatting, you would just need to set the initial indent correctly. The current format could be thought of as a range format across the whole file with the initial indent set to 0. Unless I misunderstand range formatting?

I don't know what type formatting means.

**Comment by davidanthoff** [comment]
Cool, thanks for the update.

The type formatting is a feature in VS Code that auto-formats code as you type it in the editor, see [here](https://microsoft.github.io/language-server-protocol/specification#textDocument_onTypeFormatting)

**Comment by DoktorMike** [comment]
Any updated on this with respect to the vim editor? If not I'll take a crack at it myself. :)

**Comment by domluna** [comment]
@DoktorMike haven't taken a crack at it yet. I'm using coc-vim at the moment. I wonder if there's a simple way to just have it call the formatter with a keybind. So on the initial load of a .jl it'll call `using JuliaFormatter` then `format_text` with the keybind. I guess a shell exec call could work too?

**Comment by tkf** [comment]
It's not an editor but here is my try to make it work on REPL :)
https://github.com/tkf/InteractiveFormatter.jl

**Comment by domluna** [comment]
I'll try it out tonight or tmrw.

**Comment by kdheepak** [comment]
If anyone is looking, there's this Visual Studio Code extension called [Julia Formatter](https://marketplace.visualstudio.com/items?itemName=singularitti.vscode-julia-formatter) by @singularitti that works using `JuliaFormatter.jl`.

**Comment by darrencl** [comment]
Hi,

Thanks to write code formatter for Julia!

Anyway, I am just wondering if there is any plan to integrate this with sublime text?

Thanks!

**Comment by domluna** [comment]
@darrencl I've never used it so I don't have plans myself. I don't know if anyone else has something working for Sublime Text.

**Comment by domluna** [comment]
I think this can be closed...
