### ISSUE TITLE
Emacs integration

### ISSUE THREAD

**Issue by ncihnegn** [domluna/JuliaFormatter.jl#210]
I am surprised no Emacs users raise the question.

**Comment by domluna** [comment]
I think someone was working on this but I'm not sure 🤔 . I'm a vim person myself so I personally won't be taking this up.

**Comment by StefanKarpinski** [comment]
Anything to be done on in the package for this? This seems like work to be done in the editor side.

**Comment by ncihnegn** [comment]
> Anything to be done on in the package for this? This seems like work to be done in the editor side.

You are right.
