### ISSUE TITLE
Expand format skipping

### ISSUE THREAD

**Issue by Libbum** [domluna/JuliaFormatter.jl#215]
Hi all.

I've come across some friction in our formatting rules and would like to relax the `indent` requirements for selected areas of our code. Essentially, this would mean in general we stay with the default `indent = 4` style, but some blocks we wish to override that and enforce an `indent = 2`.

Blanket [formatting skips](https://domluna.github.io/JuliaFormatter.jl/stable/skipping_formatting/) are not what we really would like, but perhaps the ability to only skip keyworded formatting could work?

```julia
#! format: [on|off]
#! indent: [on|off]
#! margin: [on|off]
```

Or complete overrides

```julia
#! indent: 2
#! margin: 80
# or perhaps
#! indent: 2 [on|off]
#! margin: 80 [on|off]
```

*etc*.

Is this something you'd consider adding? Or is there something I've missed in the documentation that would allow me to do this with the current version?

**Comment by domluna** [comment]
This could be added, but it'll be trickier to implement format disabling.

**Comment by StefanKarpinski** [comment]
I would strongly consider whether this option is a good idea or not. Is the intention to change the formatting options in the middle of a file? Or to apply different styles to different files? The comment `#! format: [on|off]` is already reasonable JuliaFormatter specific because of the word `format`. The word `indent` or `margin` are not—if you're going to add a comment-based mechanism like this, it really needs to be scoped to JuliaFormatters somehow. But I really don't think this belongs in comments in the first place. Granularity of code style at a level finer than an entire file is extremely questionable, imo.

**Comment by Libbum** [comment]
Agree with the sentiment @StefanKarpinski (hence the 'friction' in my initial post). If you think that this is essentially outside of the scope of JuliaFormatter, that's certainly fine. 

As an alternate: what about an option to make `indent` checking completely optional in the formatter?

**Comment by StefanKarpinski** [comment]
The formatter doesn't do checking, it does formatting. It needs to have a value for indent when reformatting code. Do you have different portions of code in the same file with different indent?

**Comment by domluna** [comment]
So you could do `#! format_indent: 2` or something like that. The thing I don't like about this it opens up the rabbit hole of every option being configurable on a line-by-line basis. While this may sound cool, In practice I think it would be an absolute headache.

**Comment by Libbum** [comment]
Thanks for the feedback. 

> Do you have different portions of code in the same file with different indent?

Yep :/

> Mixing formatting options/styles in the same file should probably be avoided.

I'm of the same opinion, my team: not so much. Lets leave this as a [wontfix] though, I'll go back to my team and see what else can be done internally.

**Comment by StefanKarpinski** [comment]
Yikes, different indents in the same file 😬. That's... rough. Seems like picking an indent and sticking with it—everywhere, ideally—is the way to go. If you can't collectively agree to a common indent in one file, it seems unlikely to be able to agree to a common formatting style more generally.

**Comment by kenahoo** [comment]
In case anyone ever revisits this issue, perhaps a more natural syntax would be something like this:

```
#! format: [on|off]
#! format: indent=[on|off|<number>]
#! format: margin=[on|off|<number>]
...
```

The point is to keep everything within the single `format:` directive.

I'm not really sure what the universe of possible options are, I have no opinion on that really.
