### ISSUE TITLE
autoformatting of docstrings including embedded code

### ISSUE THREAD

**Issue by bramtayl** [domluna/JuliaFormatter.jl#216]
Formatting the code in the doctests contained in docstrings would be a nice feature to have, I think.

**Comment by domluna** [comment]
sounds similar to https://github.com/domluna/JuliaFormatter.jl/issues/197 but also sounds a little different. I don't think I'm on the same page, can you give an example?

**Comment by bramtayl** [comment]
Similar, this for doc strings not comments though. https://bramtayl.github.io/LightQuery.jl/latest/ might be a good example. The gray bits are julia code. The source is here: https://github.com/bramtayl/LightQuery.jl/blob/master/docs/src/index.md

**Comment by domluna** [comment]
If you format the text in the code blocks it should just work. But that's definitely trickier than it sounds.

**Comment by bramtayl** [comment]
I tried that but I think that after the `julia> ` prompt there needs to be an indent of 6 spaces for the following lines?

**Comment by StefanKarpinski** [comment]
This is definitely harder than it sounds since I think it's equivalent to parsing docstrings and reformatting them. That said, it would be great to have autoformatting of docstrings, including embedded code, which could recursively call the Julia formatter.

**Comment by domluna** [comment]
this would be significantly easier to do in a .jl file and a .md file

**Comment by bramtayl** [comment]
I'm not sure I understand... The source code of the docs I linked is a .md file, with many of the docstrings taken from various .jl files. I'm guessing the hard part would be autoformatting markdown, and once that's done, it could be broadly applicable?

**Comment by bramtayl** [comment]
https://github.com/sumnow/markdown-formatter

**Comment by bramtayl** [comment]
I could take a stab of porting the javascript to julia?

**Comment by StefanKarpinski** [comment]
Porting a JavaScript markdown parser seems like the wrong way to go about this. We already have a Markdown parser built into Julia. Why not just build on that to emit formatted markdown?

**Comment by bramtayl** [comment]
D'oh yes that makes sense

**Comment by bramtayl** [comment]
Maybe then the best way to go about this would be to make improvements (if they are required) to the show methods for markdown in Base?

**Comment by StefanKarpinski** [comment]
Perhaps, but ideally the methods for rendering back to markdown would be added externally. It's not type piracy if the mime type is defined externally. I guess it would also be acceptable to add a method of rendering markdown back to markdown in the internal markdown module.

**Comment by bramtayl** [comment]
After further thought, Documenter.jl has a way to render markdown. So maybe it would be a good idea to have an option in Documenter to call JuliaFormatter under the hood when formatting julia code blocks?

**Comment by bramtayl** [comment]
Or maybe JuliaFormatter could make use of some of the Documenter machinery for parsing jldoctest code blocks?

**Comment by bramtayl** [comment]
This seems to work well enough:

```
using Documenter.DocTests: repl_splitter
using JuliaFormatter: format_text
using Markdown: MD, Code, plain


format_docstrings!(something_else) = nothing

function format_docstrings!(document::MD)
    for clause in document.content
        format_docstrings!(clause)
    end
    nothing
end

function format_docstrings!(doctest::Code)
    language = doctest.language
    code = doctest.code
    doctest.code = if startswith(language, "@example") ||
        startswith(language, "@repl") ||
        startswith(language, "@eval")
        format_text(code)
    elseif startswith(language, "jldoctest")
        if occursin(r"^julia> "m, code)
            join(
                (
                    join(
                        (
                            string("julia> ", line) for
                            line in split(format_text(input), '\n')
                        ),
                        "\n"
                    ) for (input, output) in repl_splitter(code)
                ),
                "\n\n"
            )
        else
            an_input, output = split(code, "# output\n", limit = 2)
            string(format_text(String(an_input)),  "# output\n", output)
        end
    else
        code
    end
    nothing
end

# test

"""
This is a docstring

\```@example
a =  1
 b  = 2
 a + b
\```

\```jldoctest
a =  1
b  = 2
a + b

# output

3
\```

\```jldoctest
julia> a =  1
1

julia> b  = 2;

julia>  a + b
3
\```
"""
function test(x) x end

docstring = @doc test
format_docstrings!(docstring)
print(plain(docstring))
```

**Comment by StefanKarpinski** [comment]
Nice! Using code that already exists for the win.

**Comment by bramtayl** [comment]
I tried making this into a PR but got lost in the internals

**Comment by domluna** [comment]
@bramtayl go ahead make the PR I'll help out
