### ISSUE TITLE
stable documentation still points to v0.3

### ISSUE THREAD

**Issue by aviatesk** [domluna/JuliaFormatter.jl#226]
Maybe https://github.com/JuliaDocs/Documenter.jl/issues/1277 will help.
@mortenpi do you think setting up `on.push.tags: '*'` or adding `ssh: ${{ secrets.DOCUMENTER_KEY }}` in [TagBot.yml](https://github.com/domluna/JuliaFormatter.jl/blob/master/.github/workflows/TagBot.yml) may solve the problem for this package ?

**Comment by domluna** [comment]
I added the key to tagbot, let's see if that solves it.

**Comment by domluna** [comment]
looks like this works now
