### ISSUE TITLE
Allow alignment on special chars

### ISSUE THREAD

**Issue by baggepinnen** [domluna/JuliaFormatter.jl#227]
I just started using JuliaFormatter and it's pretty great!
The only problem I'm facing is that it undos the nice alignment I get with
https://atom.io/packages/atom-alignment
and I have to go through the code after formatting to reapply the alignment. Would there be a way to get some alignment capabilities into julia formatter, with a custom style etc.?
To show what I mean, JuliaFormatter formats code like this
```julia
f1 = range(0.01, stop = 1, length = N)
f2 = range(0.1, stop = 1, length = N) .^ 2
g(x, N) = exp(-10 * (x - N / 2)^2 / N^2)
t = 1:N
y10 = sin.(t .* f1) .* g.(t, N)
y20 = sin.(t .* (f1 .+ 0.5)) .* g.(t, N)
q = y10 .+ 1 .* randn.()
y = [0y20; 0y20; y20; 0y20; 0y20] .+ 1 .* randn.()
```
which I find much harder to parse than the following, which is the output after alignment on the char `=`
```julia
f1      = range(0.01, stop = 1, length = N)
f2      = range(0.1, stop = 1, length = N) .^ 2
g(x, N) = exp(-10 * (x - N / 2)^2 / N^2)
t       = 1:N
y10     = sin.(t .* f1) .* g.(t, N)
y20     = sin.(t .* (f1 .+ 0.5)) .* g.(t, N)
q       = y10 .+ 1 .* randn.()
y       = [0y20; 0y20; y20; 0y20; 0y20] .+ 1 .* randn.()
```

This problem is perhaps hard to solve in general (indeed, the atom alignment package manually aligning suitable blocks) since the naive alignment would align the whole file according to the *longest* LHS. 

Maybe alignment could work only within "blocks" that are demarcated by an empty line, so that 
```julia
a = 1
bc = 2

long_variable = 1
other_var = 2
```
would align on `=` to the following
```julia
a  = 1
bc = 2

long_variable = 1
other_var     = 2
```

There would probably also have to be a "maximum LHS length", so that all left hand sides exceeding this length are ignored for alignment.

**Comment by domluna** [comment]
hey @baggepinnen we've had a similar discussion https://github.com/domluna/JuliaFormatter.jl/issues/179.

As a coincidence I was going to try to get this working in some regard in the next few days.

**Comment by baggepinnen** [comment]
Closing in favor of #179. I added my comments from this issue there
