### ISSUE TITLE
Spacing of calling named tuple/named arguments with `!`

### ISSUE THREAD

**Issue by jlperla** [domluna/JuliaFormatter.jl#242]
Take the following code
```julia
f(; a!) = a!
f(; a! = 4)
```
Obviously this is a MWE and the `!` named argument would be an inplace function, but it replicates the issue.

Now format this (I am using YAS which might have different behavior than the regular) and it makes it
```julia
f(; a!) = a!
f(; a!=4)
``` 
Which is incorrect because the the `! =` ends up together and parses as `!=`.

**Comment by domluna** [comment]
Aside from the option to be implemented from #243, the next best thing is to put parenthesis around `a!`.

**Comment by jlperla** [comment]
I think these are somewhat independent.  If people want to use an option without spaces around the named arguments, then the formatter can't generate invalid code.  

But your suggestion to add `(..)` around the calls seems to work, as far as I can tell, and is reasonably easy to read.  i.e. `f(; (a!)=4)`.  Though my preference would just be for the spaces in that case.

**Comment by jlperla** [comment]
Amazing!  Do you know the process for releasing new versions to be used by Juno?  Are you at there mercy as to when it is bumped?

**Comment by domluna** [comment]
I don't know they determine what version is used. @aviatesk do you know how that works?

**Comment by aviatesk** [comment]
I've just bumped Atom.jl's version so that it's compatible with JuliaFormatter.jl@0.6, so just wait a moment and then `] up Atom` please

**Comment by jlperla** [comment]
Great.  Just to make sure I understand the approach here.  Until a new Juno release, we should basically to to our `(v1.4)` environment and `]up Atom` and `]up JuliaFormatter`?

**Comment by aviatesk** [comment]
no no, Atom.jl@0.12.14 is already registered, so `] up` in your environment where Atom.jl and Juno.jl is loaded will automatically bump up JuliaFormatter.jl if there is no version conflicts.
`] st` will help you which version you use.
There is no need to update Atom packages (e.g. julia-client) for that.

**Comment by jlperla** [comment]
The new layout stuff largely seems to be great.  I had an issue where with `whitespace_in_kwargs = true` didn't add the spaces around returned named tuples .  That is,
```julia
function f(x;a=1,b=2)
return (a=a,b=b)
end
```
Became
```julia
function f(x; a = 1, b = 2)
    return (a=a, b=b)
end
```
Is that what the v0.6.2 release fixes?  If so, then maybe Atom should bump it again?

**Comment by domluna** [comment]
correct !
