### ISSUE TITLE
Option to put spaces around keyword arguments in YAS

### ISSUE THREAD

**Issue by jlperla** [domluna/JuliaFormatter.jl#243]
I like a lot about the YAS style with function indenting, but not that it forces a lack of spaces around keyword arguments/named tuples?

Is there any way to decouple some of these things so that you can have an option to have spaces?

In general, it would be nice if all of these things were as orthogonal as possible, so that you could fully recreate the "yas" with other options or overwrite as required.  In that sense "style = yas" could just be a bunch of defaults rather than something important unto itself. 

Alternatively, instead of modifying YAS, consider a YAS-style function indenting option which could be used in the base style.

**Comment by domluna** [comment]
makes sense, only reason I haven't done this already is because it was more involved than I thought it would be the last time I looked at it :upside_down_face:

**Comment by domluna** [comment]
I don't know why this seemed so much harder before, turns out it was super simple.
