### ISSUE TITLE
Is there an option to disable adding `Any` to unannotated field types?

### ISSUE THREAD

**Issue by singularitti** [domluna/JuliaFormatter.jl#246]
Like not reformatting
```julia
struct A
    x
end
```
to
```julia
struct A
    x::Any
end
```

**Comment by domluna** [comment]
it would be easy enough to make it an option that defaults to `on`.

Do you just not like the automatic annotation?

**Comment by singularitti** [comment]
Yes, I prefer not writing it. Thanks!
