### ISSUE TITLE
Improper formatting of division of the form 1 / 2a^2

### ISSUE THREAD

**Issue by cameronperot** [domluna/JuliaFormatter.jl#251]
JuliaFormatter Version: v0.6.4
Julia Version: 1.5.0-beta1.0

I recently ran JuliaFormatter and noticed that the output of my code changed after. I did some digging and found that it was a snippet of code like this:
```
1 / 2a^2
```
which was changed to this:
```
1 / 2 * a^2
```
Which is mathematically a different operation.

Steps to reproduce:
1. Have a line of code in a file with division by a variable raised to a power with a scalar multiplication tacked on to the left, e.g. of the form `1 / 2a^2`.
2. Run JuliaFormatter on the file.
3. Observe that the aforementioned operation has now changed to `1 / 2 * a^2`.

**Comment by domluna** [comment]
fix incoming, thanks for the great report

**Comment by cameronperot** [comment]
Happy to help :). Thanks for the quick fix!
