### ISSUE TITLE
format_text("1/2foo.a") returns "1 / 2 * foo.a"

### ISSUE THREAD

**Issue by msekino** [domluna/JuliaFormatter.jl#258]
julia> format_text("1/2a")
"1 / 2a"

however,

julia> format_text("1/2foo.a")
"1 / 2 * foo.a"

**Comment by domluna** [comment]
this looks like an older version is being used, can you check your version of JuliaFormatter?

**Comment by msekino** [comment]
Oh! I'm sorry, my pkg's version was v0.6.4.
Now I have updated the pkg to v0.6.6, it works!
Thank you!
