### ISSUE TITLE
JuliaFormatter changes empty NamedTuple `(;)` to empty Tuple `()`

### ISSUE THREAD

**Issue by nickrobinson251** [domluna/JuliaFormatter.jl#285]
In JuliaFormatter v0.7.5 (tried in Julia v1.4 and Julia v1.5)
```julia
julia> str = """
       nt = (;)
       """;

julia> print(format_text(str))
nt = ()
```

This is a bit tricky with Juia versions, since in v1.0 - v1.4 `(;)` returned `nothing`, whereas in 1.5 `(;)` returns an empty `NamedTuple` (https://github.com/JuliaLang/julia/pull/34557).
```julia
julia> VERSION
v"1.4.2"

julia> (;) == nothing
┌ Warning: Deprecated syntax `(;)` at REPL[3]:1.
│ Use `begin end` instead.
└ @ REPL[3]:1
true
```
```julia
julia> VERSION
v"1.5.1"

julia> (;)
NamedTuple()
```
Either way the current JuliaFormatter behaviour is a bug. And i guess the safest thing for JuliaFormatter to do is just not change `(;)`.

**Comment by charleskawczynski** [comment]
I just ran into this today
