### ISSUE TITLE
Array literals (hvcat) white space sensitivity 

### ISSUE THREAD

**Issue by baggepinnen** [domluna/JuliaFormatter.jl#289]
The top expressions below is formatted in an unfortunate way to the lower expression, introducing whitespaces in a white-spce sensitive context. While the formatting is correct, it makes it very hard to manually parse the expression
```julia
A =  [0. 1 0 0
   -k/Jm -c/Jm k/Jm c/Jm
    0 0 0 1
    k/Ja c/Ja -k/Ja -c/Ja]

A = [
    0.0 1 0 0
    -k / Jm -c / Jm k / Jm c / Jm
    0 0 0 1
    k / Ja c / Ja -k / Ja -c / Ja
]
```

**Comment by domluna** [comment]
this looks like a good case to not add spaces
