### ISSUE TITLE
Spurious new empty lines introduced for certain docstrings for structs.

### ISSUE THREAD

**Issue by kellertuer** [domluna/JuliaFormatter.jl#291]
First of all thanks for this nice package – it helps keeping our code nice and tidy :)

Today I updated to the `0.8` and noticed something strange. I can not yet narrow it down to an MWE, but it seems that sometimes after a `struct` a newline is introduced – even again and again and again.

We usually run `format` with the settings from https://github.com/JuliaManifolds/ManifoldsBase.jl/blob/master/.github/workflows/format.yml

But now, running for example on
https://github.com/JuliaManifolds/ManifoldsBase.jl/blob/master/src/ValidationManifold.jl

with 
````julia
format("ValidationManifold.jl",
    short_to_long_function_def = true,
    always_for_in = true,
    whitespace_ops_in_indices = true,
    pipe_to_function_call = true,
    import_to_using = true,
    always_use_return = true,
)
````

Changes the first struct from
https://github.com/JuliaManifolds/ManifoldsBase.jl/blob/8789cab9a590704cf9e151a08f45160be5b71630/src/ValidationManifold.jl#L12-L14

to
````julia
struct

ValidationManifold{𝔽,M<:Manifold{𝔽}} <: AbstractDecoratorManifold{𝔽}
    manifold::M
end
````

and running the `format` again introduces another two lines and so on, so it especially always returns `false`.

I tried narrowing it further down
* just the `struct` in a file does not reproduce the error
* just the struct with a 3 line empty doc like 
````julia
"""
    ABC
"""
struct ValidationManifold{𝔽,M<:Manifold{𝔽}} <: AbstractDecoratorManifold{𝔽}
    manifold::M
end
````
 does not reproduce the error
* the struct with the doc string as
````julia
"""
    ValidationManifold{𝔽,M<:Manifold{𝔽}} <: AbstractDecoratorManifold{𝔽}
"""
structValidationManifold{𝔽,M<:Manifold{𝔽}} <: AbstractDecoratorManifold{𝔽}
    manifold::M
end
````
_does_ reproduce the error.
Sorry that I could not narrow that down further, if I can provide any other information, I'd be happy to do so.

**Comment by domluna** [comment]
so it looks like this is unicode related, in v0.8 I had to make changes to how the State offset is incremented for aligning with unicode https://github.com/domluna/JuliaFormatter.jl/pull/282/commits/b34a99920f7c0cb57b594a4a247cf1a0b0e0906e

The test case you provided should be enough to figure it out

**Comment by domluna** [comment]
I'd use v0.7.x if you can while this is resolved though or find more unicode bugs and post them!

**Comment by kellertuer** [comment]
I started, because GitHub Actions were failing while locally it still worked!

I played a little bit and this is an MWE file content
````julia
"""
  𝔽𝔽
"""
struct A end
````
It seems that kind of a second utf8 character triggers the line after struct. So just `𝔽` is not enough.
