### ISSUE TITLE
`//` rational number constructor should use more spaces

### ISSUE THREAD

**Issue by eschnett** [domluna/JuliaFormatter.jl#297]
The `//` rational number constructor doesn't use spaces when its arguments are complex expressions:
```Julia
julia> format_text("((-1)^s * factorial(i) * factorial(n)) // (2^n * factorial(i+n))")
"((-1)^s * factorial(i) * factorial(n))//(2^n * factorial(i + n))"
```
Both numerator and denominator are long expressions that contains spaces, yet the `//` operator binds tightly without spaces. This also leads to problems with line breaks – line breaks near the `//` won't happen.

It's fine if simple expressions such as `1//2` are rendered without spaces, but that looks strange for more complex expressions.

**Comment by nickrobinson251** [comment]
This was changed in https://github.com/domluna/JuliaFormatter.jl/pull/288

Arguable `//` should have the same fanciness as ranges with `:` where `1:2` stays as `1:2` but `1:2 + 3` can be formatted as `1:(2 + 3)`

so `1//2` would stay as `1//2` and `((-1)^s * factorial(i) * factorial(n)) // 2` would become `((-1)^s * factorial(i) * factorial(n))//2`

**Comment by eschnett** [comment]
The parentheses are not the problem; the problem is that, in this case, `//` should bind as tightly as `/`.

`x//y` is not always a number. You might as well say that `x/y` is just a number. When applied to integer literals (`1//3`, `1/3`), it makes sense to treat them as number, but in general they are not – not when applied to complex expressions.

The only difference between `//` and `/` (for integer arguments) is that `//` converts to rational numbers, whereas `/` converts to floating-point numbers.

**Comment by domluna** [comment]
Hmm maybe the change in #288 should be blue style specific then?

**Comment by nickrobinson251** [comment]
i kinda feel like `/` and `//` are different in this "just a number" way `1//2` is more like `1.2` (sntactically) than it is like `1/2`, but maybe i just take repl output too seriously
```julia
julia> 1/2
0.5

julia> 1//2
1//2
```
also 🤷 😆 
I'm happy enough with `//` changes in #288 to be BlueStyle specific
