### ISSUE TITLE
Replace `in` by `∈`

### ISSUE THREAD

**Issue by eschnett** [domluna/JuliaFormatter.jl#316]
It would be nice to replace `in` by `∈` (typed `\in`). Julia accepts this for the regular operators as well as in `for` statements.

**Comment by domluna** [comment]
:smile: i knew someone would ask for this at some point

**Comment by StefanKarpinski** [comment]
Note that as an operator `∈` is just a binding, so it's not generally safe to replace `in` with `∈` or vice versa. In the `for` syntax, it is safe because it's syntactic.

**Comment by domluna** [comment]
Would something like this make sense https://github.com/domluna/JuliaFormatter.jl/pull/380 ?

**Comment by eschnett** [comment]
This looks fine. It's more general than necessary since the only three options are `i = 1:10`, `i in 1:10`, and `i ∈ 1:10`. Are you expecting to allow setting `in_replacement` to `=`?

There's also a question of spacing. `in` requires spaces on the left and right, the other two don't.

**Comment by domluna** [comment]
Either way it would add another option so at least in_replacement is more general. Spaces would be added like they are for `=`

**Comment by domluna** [comment]
Ok I've named this `for_in_replacement`. I'm not 100% sold on that name if you folks can think of something better I'm all ears.

**Comment by domluna** [comment]
There's no way to include \in as part of variable name right?

```
julia> foo(always_for_in::Bool) = 10
foo (generic function with 1 method)

julia> bar(always_for_∈::Bool) = 10
ERROR: syntax: "(always_for_ ∈ ::Bool)" is not a valid function argument name around REPL[31]:1
```

**Comment by eschnett** [comment]
No, `\in` is an operator, similar to `+`. `x+` also wouldn't be allowed, as it parses as two tokens (`x`, `+`).
