### ISSUE TITLE
StackOverflowError with style blue

### ISSUE THREAD

**Issue by kellertuer** [domluna/JuliaFormatter.jl#317]
I just play around with the `.JuliaFormatter.toml` file, a really neat approach, see our current PR https://github.com/JuliaManifolds/Manifolds.jl/pull/234.

While this works perfectly fine, I wanted to switch to the even shorter variant for code style blue, i.e. just putting one line into the style file, namely
````julia
style = "blue"
````
as mentioned in https://domluna.github.io/JuliaFormatter.jl/dev/blue_style/#Configuration-File-Example

But then starting Julia and running
````julia
julia> julia> using JuliaFormatter; format(".")
````
yields
````
ERROR: StackOverflowError:
Stacktrace:
 [1] defines_function(::CSTParser.EXPR) at ~/.julia/packages/CSTParser/uIeiO/src/interface.jl:84
````

Am I missing something or is this a bug?

**Comment by domluna** [comment]
hmm this is weird I'll look into it
