### ISSUE TITLE
Add us to `vim-autoformat` vim plug-in

### ISSUE THREAD

**Issue by Moelf** [domluna/JuliaFormatter.jl#328]
https://github.com/Chiel92/vim-autoformat

seems to be pretty modular on their end.

**Comment by domluna** [comment]
@kdheepak any thoughts on this? I've never done vim plugin development so I'm unclear what this requires

**Comment by kdheepak** [comment]
I can look into it! It should be straightforward :)

**Comment by kdheepak** [comment]
I've submitted a PR, which is linked above. Suggestions to improve the PR are welcome!

But I think users of `vim-autoformat` may not find this ideal. `vim-autoformat` spawns a `Python` job, which then spawns a `Python` subprocess to call a formatter based on the file in question. And the stdout of the `Python` subprocess is treated as the formatted text for the current buffer. 

When formatting `Julia` files, a `Julia` + `JuliaFormatter.jl` process is started each time you call `:AutoFormat` and this takes about 5-10 seconds on my mac to start up + precompile + format + print to stdout each time, and during this `vim` unfortunately _hangs_. `vim`'s `Python` integration is not asynchronous.
Additionally, for this PR to function correctly `JuliaFormatter.jl` must be installed in the `Julia` global environment, which works but is not ideal. 

I'm open to recommendations to solving this better.

However, I think vim users should just use [`JuliaFormatter.vim`](https://github.com/kdheepak/JuliaFormatter.vim) instead. It spins up a `vim` / `nvim` job, which runs a `Julia` stdout/stdin server that handles the formatting of text. This means you experience the slow formatting only the first time you format `Julia` code after opening vim. The following calls to `format_text` are all basically instant. Additionally, in `JuliaFormatter.vim`, there's a separate environment shipped with the plugin that is used to install the `JuliaFormatter.jl` and other dependencies. Nothing is installed to the global Julia environment. And lastly, there's also `PackageCompiler.jl` support. The first time to format is basically instant if you create a sysimage and enable that feature (instructions for which are in the documentation).

**Comment by Moelf** [comment]
>  a Julia + JuliaFormatter.jl process is started each time you call :AutoFormat and this takes about 5-10 seconds on my mac to start up + precompile + format + print to stdout each time

that's unfortunate, I guess using `PackageCompiler.jl` can partially mitigate this?

**Comment by kdheepak** [comment]
> that's unfortunate, I guess using PackageCompiler.jl can partially mitigate this

Yup! With PackageCompiler.jl, it is a pleasant experience.

> that's what I do, but just say that repo and saw Julia missing.

Yup, makes sense! And I added as much information about all this to the README of `vim-autoformat` in the PR. If you had suggestions to improve that let me know.

**Comment by kdheepak** [comment]
The PR is merged! This issue can be closed.
