### ISSUE TITLE
add julia-formatter.el in "Editor Plugins" for Emacs

### ISSUE THREAD

**Issue by FelipeLema** [domluna/JuliaFormatter.jl#329]
Hey, there

I'm the maintainer of [`julia-formatter.l`](https://codeberg.org/FelipeLema/julia-formatter.el). This is an Emacs package (plugin) to use JuliaFormatter.jl to format your julia code live while you code.

Can this be added into the "Editor Plugins" as a plugin for Emacs?

**Comment by domluna** [comment]
sure make a PR and I'd be happy to add it
