### ISSUE TITLE
Formatter turns good code into bad and violates margin

### ISSUE THREAD

**Issue by odow** [domluna/JuliaFormatter.jl#338]
Here's an example from JuMP: https://github.com/jump-dev/JuMP.jl/pull/2387/files#r531813190
```Julia
s = """
mock = MOI.Utilities.MockOptimizer(
    MOI.Utilities.UniversalFallback(MOI.Utilities.Model{Float64}())
)
"""
format_text(s; margin = 80)

# yields

mock =
    MOI.Utilities.MockOptimizer(MOI.Utilities.UniversalFallback(MOI.Utilities.Model{Float64}()))
```

**Comment by domluna** [comment]
this is the behavior for when there's a singular arg in (...), {...}, [...]

this could be revisited or tinkered with but there are instances where it does result in a nicer format

**Comment by domluna** [comment]
hmmm looking more at this and I'm leaning towards making this change now. It also is more consistent behavior on the formatter's end.

**Comment by odow** [comment]
I would expect the rule is: 
 - Does the line fit on one line?
 - If no, drop the outer argument. Does it fit on one line? Recurse.

That would result in things like this:
```Julia
mock = MOI.Utilities.MockOptimizer(
    MOI.Utilities.UniversalFallback(MOI.Utilities.Model{Float64}())
)

# or, if margin even shorter

mock = MOI.Utilities.MockOptimizer(
    MOI.Utilities.UniversalFallback(
        MOI.Utilities.Model{Float64}()
    )
)
```

**Comment by nickrobinson251** [comment]
i _think_ `BlueStyle` has these line break and indent rules

**Comment by domluna** [comment]
This is going to require creating an `unnest` type function similar to the way `pretty` or `nest` currently work. The current un-nesting mechanism makes some big assumptions for simplicity and is not extendable. This would be a good change overall, it's just a bit more involved than I originally hoped.

**Comment by domluna** [comment]
@odow as of 0.12 this now formats as

```
julia> format_text(s; margin = 80) |> println
mock = MOI.Utilities.MockOptimizer(
    MOI.Utilities.UniversalFallback(MOI.Utilities.Model{Float64}()),
)
```
