### ISSUE TITLE
for = vs for in normalization

### ISSUE THREAD

**Issue by StefanKarpinski** [domluna/JuliaFormatter.jl#34]
The rule of thumb that I use for `for` loops is that if the thing you're iterating over is a literal range then you use `=` whereas if it's anything else (e.g. an object) then I use `in`. So, for example, these would be "correct":
```jl
for i = 1:n
    println(i)
end

for i in itr
    println(i)
end
```
These, on the other hand would be "incorrect":
```jl
for i in 1:n
    println(i)
end

for i = itr
    println(i)
end
```
Part of the reasoning is that `for i = 1:n` looks like it assigns `i` to 1, then 2, then ... `n` — at least in common mathematical / pseudocode notation, whereas `for i = itr` looks like it assigns `i = itr` which is not what it does. So one could argue "why use/allow `for i = 1:n` at all? Why not just use `in` uniformly and write `for i in 1:n` and `for i in itr`? Some people surely would prefer this. However, this superficial syntax difference can help catch a common error, which is writing `for i = n` when you meant to write `for i = 1:n`. If we require `in` there then the programmer will notice that `for i in n` is not what they meant to write and catch the bug.

So I would propose normalizing `for =` versus `for in` based on this rule. Thoughts?

**Comment by domluna** [comment]
I'm in favour of this. 

Throwback https://github.com/julia-vscode/DocumentFormat.jl/pull/26/files#diff-8f8b649677f922163282f3d951be629aR89-R104.

Additionally this is a best practice for the prevalent style guides:

- http://www.juliaopt.org/JuMP.jl/latest/style.html
- https://github.com/jrevels/YASGuide

**Comment by KwatME** [comment]
Good idea.

**Comment by diegozea** [comment]
> why use/allow for i = 1:n at all? Why not just use in uniformly and write for i in 1:n and for i in itr? Some people surely would prefer this.

I'm some people. I've found `for =` difficult to read, so I always use `for in`. I would prefer `for ∈` instead of `for =` if a difference should be made.

**Comment by KwatME** [comment]
It's more difficult to type ∈. Also, ∈ is rarely found in other languages.

**Comment by singularitti** [comment]
I am "some people" also. In fact, some [nonofficial guide](https://github.com/jrevels/YASGuide/blob/master/README.md#L71) has suggested not to use `for ... = ...`.

**Comment by KwatME** [comment]
I'm for always using `in`.

**Comment by odow** [comment]
Going to chime in on this dead issue that
> Additionally this is a best practice for the prevalent style guides: 
>  - http://www.juliaopt.org/JuMP.jl/dev/style/

Is incorrect. JuMP's rule is to _always_ prefer `in` over `=`.

> Part of the reasoning is that for i = 1:n looks like it assigns i to 1, then 2, then ... n — at least in common mathematical / pseudocode notation, whereas for i = itr looks like it assigns i = itr which is not what it does.

You could (and I will) argume that `i = 1:n` looks like it assigns `i` to the iterable `1:n`.

**Comment by KwatME** [comment]
https://github.com/jrevels/YASGuide also recommends using `in` over `=`. @domluna , is it difficult to update the code to use `in` instead of `=`?

**Comment by tk3369** [comment]
I also opt for `in` over `=` in all circumstances although my visual cortex interprets them the same anyways.  I love `∈` because it's cool but often it's just too much to type and so `in` wins.

**Comment by Roger-luo** [comment]
Is there a way to choose different syntax guide? like this one. I also opt for in over = in all circumstances...

**Comment by StefanKarpinski** [comment]
No, there are currently no formatting options.
