### ISSUE TITLE
`format` changes empty NamedTuple to empty Tuple

### ISSUE THREAD

**Issue by ericphanson** [domluna/JuliaFormatter.jl#343]
with JuliaFormatter v0.11,
```julia
julia> format_text("(;)")
"()"
```
As of https://github.com/JuliaLang/julia/issues/30115 (i.e. Julia 1.5) this is valid syntax for a NamedTuple.

**Comment by domluna** [comment]
have to double check if CSTParser supports this atm

**Comment by domluna** [comment]
CSTParser doesn't parse the semicolon so I'll have to look for that similar to the way it's done for parameters or matrices

**Comment by domluna** [comment]
ref https://github.com/julia-vscode/CSTParser.jl/issues/207

**Comment by nickrobinson251** [comment]
https://github.com/domluna/JuliaFormatter.jl/issues/285

**Comment by ericphanson** [comment]
Oops, missed that one— closing as duplicate
