### ISSUE TITLE
Keyword arguments get space around = by default

### ISSUE THREAD

**Issue by rikhuijzer** [domluna/JuliaFormatter.jl#344]
When running JuliaFormatter v0.11.0, I noticed that the keyword arguments get a space around `=` by default. If I understand correctly, the Julia default is to have no spaces, like for example, in [the documentation](https://docs.julialang.org/en/v1/manual/functions/#Keyword-Arguments). 

An example of a change by JuliaFormatter.jl is
```
Pkg.add(PackageSpec(name="Documenter", version="0.25.2"))
```
into 
```
Pkg.add(PackageSpec(name = "Documenter", version = "0.25.2"))
```
after using 
```
format(".")
```
Should this be the default behavior?

**Comment by domluna** [comment]
You can set the option to false in https://domluna.github.io/JuliaFormatter.jl/dev/api/#JuliaFormatter.format_text-Tuple{AbstractString}

 whitespace_in_kwargs = false

**Comment by domluna** [comment]
It's been true since the inception of the project so for backwards compat reasons it stayed that way. I don't think the Julia language has a  definitive stance on it, the code in the repo itself it inconsistent with respect to styling.

**Comment by rikhuijzer** [comment]
Okay, that solves it for me. Thanks!
