### ISSUE TITLE
allow version info in `.JuliaFormatter.toml`?

### ISSUE THREAD

**Issue by ericphanson** [domluna/JuliaFormatter.jl#348]
One issue I've run into is that due to bugfixes etc, sometimes new versions of JuliaFormatter format things differently than older versions. That's of course expected, but in order to avoid spurious diffs (or even the same changes going back and forth as different people re-format with different versions of JuliaFormatter), it's important to specify/control the version of JuliaFormatter used. I think a reasonable place to put that specification might be inside the `.JuliaFormatter.toml` file itself, so that that one file dictates the formatting that you get. I imagine it could look like

```toml
julia_formatter_version = "0.11"
julia_version = "1.5"
```
(Though maybe `julia_version` isn't needed).
Currently, looking at the code, this will just error since it will pass these as keyword arguments to `format`. One way to support this feature is to just strip out these keys and let external tools use them (e.g. a GHA workflow could read the file and choose the correct version of Julia + JuliaFormatter to use), or possibly just throw an error if the versions in the file do not match the versions of the running Julia session. 

Another option is to spin up a new Julia process and create a temporary environment and install the right version of JuliaFormatter there, then use that to format. Something like that might make more sense as an extension of the CLI script rather than as part of the library function `format`.

Any thoughts on this? I'm happy to help implement it if it seems like a good approach.

**Comment by domluna** [comment]
The general concept makes sense but I don't know if having this in the .toml file is the best approach. I also realize adding JuliaFormatter as a dependency might not be ideal either since it's a development tool and not related to the actual project, much like Revise.

> (Though maybe julia_version isn't needed).
Currently, looking at the code, this will just error since it will pass these as keyword arguments to format. One way to support this feature is to just strip out these keys and let external tools use them (e.g. a GHA workflow could read the file and choose the correct version of Julia + JuliaFormatter to use), or possibly just throw an error if the versions in the file do not match the versions of the running Julia session.

> Another option is to spin up a new Julia process and create a temporary environment and install the right version of JuliaFormatter there, then use that to format. Something like that might make more sense as an extension of the CLI script rather than as part of the library function format.

I'm in favour of whatever is simplest/easiest on the user. I don't think passing the version arguments to format is ideal and would lean towards having a separate env if that's not too problematic.

**Comment by ericphanson** [comment]
Hm, what about this? `.JuliaFormatter.toml` allows (but of course doesn't require) a `julia_formatter_version` key. When that config is applied, if the key exists and the value doesn't match the current version of JuliaFormatter, it throws an error. I think that's pretty simple/easy; kind of an opt-in version requirement. The check wouldn't need to be part of `format` but instead could be checked during config parsing, and it could strip out that key before passing the rest to `format` as keyword arguments.

Then for tooling, I can update the GHA workflows to read the version out of the `.JuliaFormatter.toml` if it exists and use that to choose the version to install. For the CLI script, I think it's a bit annoying to have it install in a temp environment every time, but it could use shared environments, like `] activate --shared julia_formatter_0_11_1` for v0.11.1 (which it creates if it doesn't exist already), so then it only needs to run the resolver and install JuliaFormatter if it's a new version that doesn't already have an environment. But for atom/vscode integration, I'm not totally sure since I haven't used those...

**Comment by domluna** [comment]
That sounds like it could work :+1:

**Comment by ericphanson** [comment]
I had a helpful chat with @SimonDanisch about this, and he pointed out that once the project is fairly mature, the same .JuliaFormatter.toml should lead to the same formatting on most recent versions, and therefore he didn’t think the version should be seen as part of the config for how you want to format it.

Simon advocating pinning the version elsewhere (e.g. in Dockerfile or a project+manifest in a `format` subdirectory). I think I’ll try things in that direction and close this for now at least.
