### ISSUE TITLE
Documentation for how to incorporate in GitHub Actions CI workflow

### ISSUE THREAD

**Issue by st--** [domluna/JuliaFormatter.jl#350]
Currently this repo's README simply links to https://github.com/julia-actions/julia-format, which has a very nice and straightforward example, which only upon second reading of _its_ README realized is supposedly deprecated (I asked for clarification in https://github.com/julia-actions/julia-format/issues/15). It might be more helpful / less confusing to new users if this repo's README linked directly to the https://github.com/julia-actions/julia-format/blob/master/workflows/format_check.yml that now seems to be recommended? Or maybe even include that as an example in this repo (so it can more easily stay in sync with any changes you may make)?

**Comment by domluna** [comment]
updated the README in examples in julia-format repo

closing this
