### ISSUE TITLE
Add option for deleting trailing white spaces

### ISSUE THREAD

**Issue by charleskawczynski** [domluna/JuliaFormatter.jl#351]
I know I'd turn this on :)

**Comment by StefanKarpinski** [comment]
Why would one want to preserve (semantically insignificant) trailing whitespace?

**Comment by charleskawczynski** [comment]
🤷🏻‍♂️

**Comment by domluna** [comment]
Seeing as how trailing whitespace is removed I'm assuming this is for preserving that whitespace as Stefan mentioned? Probably not gonna happen - at least I don't see the benefit of something like this. And from an implementation perspective it's way more involved that what we currently do, which is ignore it, so nothing.

**Comment by charleskawczynski** [comment]
Ok, not a big deal at all, I didn't realize this would be a problem.

**Comment by StefanKarpinski** [comment]
Are you talking about semantically significant trailing whitespace like in a multiline string literal?

**Comment by charleskawczynski** [comment]
I just mean, like this 😅:

<img width="478" alt="Screen Shot 2021-01-13 at 10 00 58 AM" src="https://user-images.githubusercontent.com/1880641/104490935-60074580-5586-11eb-8773-cbe9590f7d4b.png">

**Comment by charleskawczynski** [comment]
Just read about multi-line literals. I hadn’t thought of that when I opened this issue. Being that these spaces are semantically significant, it seems like removing trailing white spaces is maybe not trivial. I’m fine with closing this issue. Thanks for the feedback

**Comment by StefanKarpinski** [comment]
To clarify: my understanding is that JuliaFormatter already removes any insignificant trailing whitespace and leaves significant trailing whitespace intact. It would be weird to preserve insignificant trailing whitespace since the package normalizes whitespace in general and removing insignificant trailing whitespace is just a special case of that. It would be incorrect to remove significant trailing whitespace since it would change the behavior of the program.

**Comment by charleskawczynski** [comment]
Ah, ok, thanks for the clarification. Maybe we're just not using the right options, then. Ohhh, I went and found what I thought was a counter example, but I realized that the trailing space was in a comment.. I imagine these understandably are ignored. I'll close this issue. Thanks!

**Comment by domluna** [comment]
Yep trailing whitespace in docstrings and comments are ignored
