### ISSUE TITLE
RFC: YASStyle join lines only if already joined in original source

### ISSUE THREAD

**Issue by domluna** [domluna/JuliaFormatter.jl#359]
Current `YASStyle` behaviour lifts all arguments onto the same line during the `pretty` stage and then breaks them onto separate lines based where the margin exceeds the maximum margin.

### Current Behaviour

```julia
# original source
somecall(arg1, arg2, arg3,
         arg4, arg5)

# during pretty stage
somecall(arg1, arg2, arg3, arg4, arg5)

# format after initial break
somecall(arg1, arg2, arg3, arg4,
         arg5)
```

This proposal maintains the argument structure of the original source code meaning **a line break can only occur between arguments originally on the same line**. As a note, this is how Vcat/TypedVcat YASStyle was implemented since in that case the syntax can alter semantics (type evaluating to a Vector vs a Matrix).  https://github.com/domluna/JuliaFormatter.jl/pull/357

### Proposed Behaviour

```julia
# original source
somecall(arg1, arg2, arg3,
         arg4, arg5)

# during pretty stage (no change!)
somecall(arg1, arg2, arg3,
         arg4, arg5)

# format after initial break
somecall(arg1, arg2,
         arg3, 
         arg4, arg5)
```

cc @ericphanson @SimonDanisch

**Comment by ericphanson** [comment]
That seems like it be useful and give a bit more control to the coder to be able to help with clarity in various situations. I’m not totally sure of how that rule might manifest itself in various situations. Was there a motivating use case that brought this idea about?

**Comment by domluna** [comment]
> That seems like it be useful and give a bit more control to the coder to be able to help with clarity in various situations. I’m not totally sure of how that rule might manifest itself in various situations. Was there a motivating use case that brought this idea about?

Not particularly. I just figured it might be a good idea to extend this to other scenarios besides vcat semantics since it could provide a bit more control. YASGuide allows you to split up arguments in a variety of ways so this would reflect that more closely.

**Comment by ericphanson** [comment]
Cool, that sounds good to me. I suspect @ararslan might have an opinion, so I’ll tag him 🙂

**Comment by ararslan** [comment]
My opinion is +1 to this. :slightly_smiling_face:

**Comment by jrevels** [comment]
xref https://github.com/domluna/JuliaFormatter.jl/issues/423 ?

**Comment by ericphanson** [comment]
closed by https://github.com/domluna/JuliaFormatter.jl/pull/534?
