### ISSUE TITLE
`whitespace_in_kwargs=false` can lead to parsing errors

### ISSUE THREAD

**Issue by ericphanson** [domluna/JuliaFormatter.jl#360]
For example,

```julia
julia> using JuliaFormatter

julia> format_text("(; g = >=(1))"; whitespace_in_kwargs=false)
ERROR: Parsing error for formatted text:

(; g=>=(1))

 Error occured on line 1, offset 10.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] format_text(cst::CSTParser.EXPR, style::DefaultStyle, s::JuliaFormatter.State)
   @ JuliaFormatter ~/.julia/packages/JuliaFormatter/6E8zi/src/JuliaFormatter.jl:365
 [3] format_text(text::String, style::DefaultStyle, opts::JuliaFormatter.Options)
   @ JuliaFormatter ~/.julia/packages/JuliaFormatter/6E8zi/src/JuliaFormatter.jl:324
 [4] #format_text#161
   @ ~/.julia/packages/JuliaFormatter/6E8zi/src/JuliaFormatter.jl:316 [inlined]
 [5] #format_text#160
   @ ~/.julia/packages/JuliaFormatter/6E8zi/src/JuliaFormatter.jl:310 [inlined]
 [6] top-level scope
   @ REPL[14]:1
```

This can be fixed by the user by adding parenthesis:

```julia
julia> format_text("(; g = (>=(1)))"; whitespace_in_kwargs=false)
"(; g=(>=(1)))"
```

So I guess one option is for `whitespace_in_kwargs=false` to automatically add those parens when needed. It could also just not remove spaces when doing so would produce invalid syntax, and let the user decide how to fix it.

Also, I had a bit of trouble tracking this down today because it seemed like the line number was wrong as well. I can reproduce this by adding `(; g = (>=(1)))` into https://github.com/domluna/JuliaFormatter.jl/blob/05b692c424efa922f29e0d5bcf1ede80785b3af4/src/JuliaFormatter.jl and formatting, and checking where the line number is reported. I added `(; g = (>=(1)))` in a new line at line 485 of the file, and the error message reported back "Error occured on line 585, offset 67."

**Comment by nickrobinson251** [comment]
this can happen due to the syntax on the LHS too e.g. given a function with a keyword like
```julia
julia> f(x; bang! = push!) = bang!(x, 1)
f (generic function with 1 method)

julia> f([3, 4])
3-element Array{Int64,1}:
 3
 4
 1
```
No space (and no parens) gives invalid syntax:
```julia
julia> f([3, 4]; bang!=pushfirst!)
ERROR: syntax: invalid keyword argument syntax "(bang != pushfirst!)" around REPL[21]:1
Stacktrace:
 [1] top-level scope at REPL[21]:1
```
valid syntax would be
```julia
julia> f([3, 4]; bang! = pushfirst!)
3-element Array{Int64,1}:
 1
 3
 4

julia> f([3, 4]; (bang!)=pushfirst!)
3-element Array{Int64,1}:
 1
 3
 4
 
julia> f([3, 4]; (bang!)=(pushfirst!))
3-element Array{Int64,1}:
 1
 3
 4
 ```

I'm not sure wish solution is preferable here (between not removing the space between the keywords in these cases, or adding parentheses as needed).

**Comment by domluna** [comment]
this now will had parenthesis in these cases

**Comment by domluna** [comment]
Btw the line info is gotten  from CSTParser so that's a bug for it (might be solved in CSTParser 3)
