### ISSUE TITLE
Slim down dependencies

### ISSUE THREAD

**Issue by davidanthoff** [domluna/JuliaFormatter.jl#366]
I'm wondering whether we could slim down the dependencies a bit? We're trying to keep the VS Code story somewhat lean :)

Couple of ideas:
- Instead of DataStructures.jl, could this package work with just OrderedCollections.jl? We already ship the latter with the extension.
- I think CommonMark.jl is actually really needed to format markdown stuff, right? That is pulling a fair number of additional things in, so that is not super ideal from the VS Code extension's point of view. I looked through the list of packages, I think they would probably all be ok to include, but it does add a lot more submodules... Maybe we just have to live with that?
- Is there some way to remove the dependency on Documenter.jl? That is a heavy dependency, and it seems that it only uses a very small part of the functionality from there? Not entirely clear to me what is actually needed from there and whether it would be easy to somehow solve this differently?

CC @pfitzseb and @ZacLN

**Comment by domluna** [comment]
DataStructures is used to an interval tree like data structure so if we could use OrderedCollections for that then cool.

CommonMark is required for formatting docstrings

I think we only use `repl_splitter` from Documenter so depending on the internals of that we may be able to remove Documenter

**Comment by davidanthoff** [comment]
I just looked at `repl_splitter`. I think if we just copied everything from [this line](https://github.com/JuliaDocs/Documenter.jl/blob/dffba5fcdb314b227f65c0164a2f78c68d1d3ece/src/DocTests.jl#L446) down, we should have it covered? That is a bit code duplication, but it seems like enough of a self-contained piece of code that that might be ok?

I'll investigate the OrderedCollection.jl idea now.

**Comment by davidanthoff** [comment]
Ok, I looked into the DataStructures.jl situation, and I think the stuff that is needed only is in DataStructures.jl, so my idea with OrderedCollections.jl won't work. So I guess we might just have to include DataStructures.jl and Compat.jl as well...
