### ISSUE TITLE
Multiline docstrings gain spaces

### ISSUE THREAD

**Issue by diegozea** [domluna/JuliaFormatter.jl#38]
Before:
```julia
"""Free space in Gb at the given path."""
free_space(path) = shutil.disk_usage(path)[3] / 1000_000_000
```

After executing *Juno*'s `Julia Client: Format Code` 1 time:
```julia
"""
Free space in Gb at the given path.
"""
free_space(path) = shutil.disk_usage(path)[3] / 1000_000_000
```

After executing *Juno*'s `Julia Client: Format Code` 2 times:
```julia
"""

Free space in Gb at the given path.
"""
free_space(path) = shutil.disk_usage(path)[3] / 1000_000_000
```

**Comment by domluna** [comment]
@diegozea I'm trying to reproduce in repl and calling `format_file` on a file with your input but I'm just getting the same result as after 1 format.

Maybe it's a Juno issue?

**Comment by diegozea** [comment]
I see the same problem using `format_file` from the REPL. (Julia 1.1 JuliaFormatter 0.1.3)

**Comment by domluna** [comment]
@diegozea can you provide a file where so I can reproduce this?
