### ISSUE TITLE
 indentation bug with YASStyle (?)

### ISSUE THREAD

**Issue by ericphanson** [domluna/JuliaFormatter.jl#387]
https://github.com/JuliaDSP/DSP.jl/pull/401/commits/dee38ad3e2c41fb05d4e08884fed1e84f70a7ee0#diff-7eb8d556545d1576a135ef609daf44651b1cf2cd46735cb90991b0ffac1b91deR39-R50

this looks strange; I formatted with JuliaFormatter v0.13.5 (Tokenize.jl v0.5.13 to avoid #386) via `format("src/multitaper_spectrogram.jl", style=YASStyle())`. I don't think it should suddenly put all these arguments way indented!

**Comment by domluna** [comment]
this is due to kind of odd parsing where `(...)` is not treated as a tuple but rather a collection of individual nodes/tokens so it throws the indentation off

**Comment by domluna** [comment]
@ericphanson can you verify https://github.com/domluna/JuliaFormatter.jl/pull/394?

**Comment by ericphanson** [comment]
Yes, looks much much better!

https://github.com/JuliaDSP/DSP.jl/pull/401/commits/e476fef6fa7767d5f0781a8a6e7a19faa62ebe74#diff-42b63c32cfe9564f97f2b1c492af2a473460ca00579a8c2ae854db0741ad7f82R42-R47

Bug looks fixed to me!

It seems like there's an unusual tradeoff to make between how many type parameters to put on a line vs how many arguments, since more type parameters mean less room per line for the arugments. I think in this case it might be worth making one more line for the type parameters so that the arguments aren't so squished up together, but I understand it might be hard to find the best balance in general.

**Comment by domluna** [comment]
https://github.com/domluna/JuliaFormatter.jl/issues/359 may help with that but it's all subjective so it's tricky to figure out what's "best"
