### ISSUE TITLE
JuliaFormatter breaks some arrays

### ISSUE THREAD

**Issue by Klafyvel** [domluna/JuliaFormatter.jl#39]
Hi !
I run into an issue using JuliaFormatter (great tool btw), it breaks some arrays (when using only a semicolon)

Example :

```julia
A = [1:3;]
B = [4; 5; 6]
println(A .+ B)
```

Will be turned in

```julia
A = [1:3] # <- here is the issue, the last `;` is removed.
B = [4; 5; 6]
println(A .+ B)
```

which does not work.

**Comment by StefanKarpinski** [comment]
The infamous significant trailing semicolon!

**Comment by domluna** [comment]
Tbh I don't remember why I made it remove the final semicolon. @StefanKarpinski is there a harm in adding a trailing semicolon?

This wouldn't add a semicolon to `[1:3]` since it would be parsed as `CSTParser.Vect` whereas `[1:3;]` is parsed as `CSTParser.Vcat`.

**Comment by StefanKarpinski** [comment]
I'd say that it's idiomatic to only keep the trailing semicolon when there's only one entry. So you'd have `[1:3;]` (trailing semicolon) but `[1:3; 4:6]` (no trailing semicolon). Make sense?
