### ISSUE TITLE
Consider adding a directory mode

### ISSUE THREAD

**Issue by adsharma** [domluna/JuliaFormatter.jl#397]
https://github.com/adsharma/py2many, a python -> Julia transpiler uses this code to format generated Julia.

It would be nice to have JuliaFormatter support directory mode, where all files (recursively) in that directory are formatted.
We are also sensitive to startup overheads. So minimizing the overall runtime would be great!

More details in https://github.com/adsharma/py2many/issues/14

**Comment by domluna** [comment]
> It would be nice to have JuliaFormatter support directory mode, where all files (recursively) in that directory are formatted.
We are also sensitive to startup overheads. So minimizing the overall runtime would be great!

this is the current behaviour

**Comment by domluna** [comment]
Startup time is a priority after CSTParser3 stuff is merged

**Comment by adsharma** [comment]
Please merge this into any existing issues about startup time, so we can follow along. Thanks!

**Comment by domluna** [comment]
#356
