### ISSUE TITLE
Bug in weird edge case with docstrings

### ISSUE THREAD

**Issue by ericphanson** [domluna/JuliaFormatter.jl#405]
For some reason, I was doing this:
```julia
module MyPkg

str = "a"
function f end
function __init__()
    @doc """
    Here's a docstring for `f` that includes dynamic content: $(str).
    """
    f
end
end
```
(where `str` is actually `PyObject` populated at init time.... The idea is to autogenerate parts of Julia docstrings from Python ones for a wrapper package).

This does seem to work, but JuliaFormatter (with `style=YASStyle()`) converts it to
```julia
module MyPkg

str = "a"
function f end
function __init__()
    @doc """
    Here's a docstring for `f` that includes dynamic content: $(str).
    """
    return f
end
end
```
which then errors because it can't document `return f`. Somehow it should turn this into
```julia
module MyPkg

str = "a"
function f end
function __init__()
    @doc """
    Here's a docstring for `f` that includes dynamic content: $(str).
    """
    f
    return nothing
end
end
```
instead.

Edit: it’s open source now, so for context the case where this came up is https://github.com/beacon-biosignals/CatBoost.jl/blob/a548b0bd58ca2a1c2f17cf65c0565420ae0f1b47/src/CatBoost.jl#L58

**Comment by domluna** [comment]
edge case related to the always adding returns option

**Comment by ericphanson** [comment]
Awesome, thanks!
