### ISSUE TITLE
Error formatting nested for...in

### ISSUE THREAD

**Issue by mehalter** [domluna/JuliaFormatter.jl#419]
I am running into a bug that causes the formatter to error on nested `for..in` calls. Here is a minimal example that causes an error:

```
x = [[1,2,3], [4,5,6]]
print([z for y in x for z in y])
```

Let me know if there is a way to fix this, I'm not sure what the best approach would be. The following code works with the formatter, but doesn't produce the appropriate list and instead produces generators:

```
x = [[1,2,3], [4,5,6]]

print([(z for z in y) for y in x])
```

**Comment by domluna** [comment]
@mehalter what version are you on this works fine for me on 0.14.4

```
julia> s = """
       x = [[1,2,3], [4,5,6]]
       print([z for y in x for z in y])
       """
"x = [[1,2,3], [4,5,6]]\nprint([z for y in x for z in y])\n"

julia> format_text(s)
"x = [[1, 2, 3], [4, 5, 6]]\nprint([z for y in x for z in y])\n"

julia> format_text(s) |> print
x = [[1, 2, 3], [4, 5, 6]]
print([z for y in x for z in y])

julia>

julia> s1 = """
       x = [[1,2,3], [4,5,6]]

       print([(z for z in y) for y in x])
       """
"x = [[1,2,3], [4,5,6]]\n\nprint([(z for z in y) for y in x])\n"

julia> format_text(s1) |> print
x = [[1, 2, 3], [4, 5, 6]]

print([(z for z in y) for y in x])
```

**Comment by mehalter** [comment]
@domluna I am also using v0.14.4. I did some more testing and it looks like it only occurs when I'm using the `style = "yas"`
