### ISSUE TITLE
Change formal.jl script to show help when called without arguments

### ISSUE THREAD

**Issue by karlwessel** [domluna/JuliaFormatter.jl#42]
At the moment, the `format.jl` script formats every `.jl`-file it can find in the current path when it is called without any argument. 

For stupid people like me this can lead to format every `.jl`-file in their whole home directory when they call it without any argument.

Maybe it would be more safe to print some usage information when called without any arguments instead of happily formating the .julia directory (and everything else)? :-)

Also some output on which file it is currently formating would probably be good.

**Comment by domluna** [comment]
fixed by #48

**Comment by karlwessel** [comment]
Thanks!
