### ISSUE TITLE
do not remove style-compliant linebreaks

### ISSUE THREAD

**Issue by jrevels** [domluna/JuliaFormatter.jl#423]
I'd like to expand the line length limit in my project via setting `margin` fairly high. However, reformatting after doing this will cause JuliaFormatter to try to fit everything on one line:

```diff
@@ -63,8 +63,7 @@ end
 function upsert(target::HasuraHTTPTarget, table_name, row; returning=["__typename"])
     mutation_target_name = string("upsert_", table_name)
     mutation_argument_name = :objects
-    mutation = (query=hasura_insert_mutation_string(mutation_target_name, mutation_argument_name, returning),
-                variables=to_hasura_gql((; mutation_argument_name => [row])))
+    mutation = (query=hasura_insert_mutation_string(mutation_target_name, mutation_argument_name, returning), variables=to_hasura_gql((; mutation_argument_name => [row])))
     response = HTTP.post(target.url, target.headers, JSON3.write(mutation))
     response_json = JSON3.read(String(response.body))
     if haskey(response_json, :data)
```

Both the "before" and "after" representations are YAS-compliant, but I as the author prefer the former representation. My naive opinion is that if code is already compliant with the chosen style guide, it should generally be considered to be in the purview of "author's choice" and left alone.

Is there a way for me to disable this behavior?

**Comment by jrevels** [comment]
xref https://github.com/domluna/JuliaFormatter.jl/issues/359 ?

**Comment by domluna** [comment]
yeah this should format how you would want once #359 is implemented

**Comment by domluna** [comment]
@jrevels I have a prototype of this https://github.com/domluna/JuliaFormatter.jl/tree/dl/423 which repo + options would be good to run this on?

**Comment by jrevels** [comment]
One of the repos where this comes up often for me is private, but I can run things with that branch and report back! Will hopefully time to do so later this week

**Comment by kleinschmidt** [comment]
Looks like that ref was deleted...is there any path forward for this feature?

**Comment by ericphanson** [comment]
cool! Could we make this the default for YASStyle? I guess as a breaking change?

**Comment by domluna** [comment]
yeah that's why i didn't make it default :-)

**Comment by ericphanson** [comment]
I think it's a bit of a BDFL situation (@jrevels) although I'm not sure that's ever been formalized

**Comment by jrevels** [comment]
AFAICT the decision to make this a default is kind of orthogonal to the YASGuide itself, I guess, but FWIW I vote we make it a default :)
