### ISSUE TITLE
Align Matrix Columns

### ISSUE THREAD

**Issue by JakobAsslaender** [domluna/JuliaFormatter.jl#425]
Hi,

First of all, thanks for this nice package! I am wondering if there is reason behind this behavior or I got some setting wrong, but when I have a matrix formatted like this:

![Screen Shot 2021-06-09 at 2 24 04 PM](https://user-images.githubusercontent.com/51003502/121408386-5c59ce00-c92e-11eb-9272-cccf97143826.png)

and I run the formatter, I get this:

![Screen Shot 2021-06-09 at 2 25 00 PM](https://user-images.githubusercontent.com/51003502/121408503-7bf0f680-c92e-11eb-9e80-6f6c99258082.png)

which is not very readable. Is there a way to format matrices so that the columns align?

Thanks a lot in advance!

**Comment by domluna** [comment]
yes there is! I just haven't gotten around to it yet but it would similar to how we align other things, demonstrated by the `align*` options

**Comment by JakobAsslaender** [comment]
Great, can't wait to see it implemented! Thanks again for all your effort!

**Comment by domluna** [comment]
@JakobAsslaender is it typical for the 0s (in the above example) to be aligned to the right instead of the left?

**Comment by JakobAsslaender** [comment]
I don't know if there is consensus about this, I just find it clearer. In fact, the LaTeX formatter does a left-align:
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/51003502/124832174-400b7a00-df4a-11eb-9a42-b872e8d931cc.png">
