### ISSUE TITLE
`return` keyword added to already style-compliant `function...end` blocks

### ISSUE THREAD

**Issue by jrevels** [domluna/JuliaFormatter.jl#426]
somewhat similar to #423 

IMO (though perhaps it's arguable) the following code is  YAS-compliant:

```jl
function f(x)
    x == 1 && return "a"
    x == 2 && return "b"
    throw(ArgumentError("x must be 1 or 2"))
end
```

JuliaFormatter currently applies this diff:

```diff
-   throw(ArgumentError("x must be 1 or 2"))
+   return throw(ArgumentError("x must be 1 or 2")) 
```

It seems like JuliaFormatter is trying to apply this rule:

> The return keyword should never be omitted from return statements within any other context (function ... end, macro ... end, etc.).

But in this example, all actual return statements DO already correctly have explicit `return`s instead of implicit returns. 

I guess an argument could be made that `throw` is not a syntax-level keyword, so we shouldn't/can't treat it specially...but it is at least a Julia builtin...

Maybe this is unsolvable though, since I could do:

```
const f = throw

function f(x)
    x == 1 && return "a"
    x == 2 && return "b"
    f(ArgumentError("x must be 1 or 2"))
end
```

and it'd be much harder to argue that the last line shouldn't be transformed to `return f(...)` barring the incorporation of non-local information

**Comment by domluna** [comment]
yeah this is tricky although is `throw` used in any other context besides this? It would be easy to add a check to see if the func name is `throw`

**Comment by jrevels** [comment]
> It would be easy to add a check to see if the func name is throw

Actually I think this would be suitable to resolve this issue in most of my own cases
