### ISSUE TITLE
Space before commas while parsing global and local

### ISSUE THREAD

**Issue by abelsiqueira** [domluna/JuliaFormatter.jl#431]
Parsing `global` and `local` with more than one argument adds a whitespace before commas:
- `global a=2,b` -> `global a = 2 , b`.
- `local a,b` -> `local a , b`.
- https://github.com/JuliaSmoothOptimizers/CaNNOLeS.jl/pull/27/files#diff-7da4614cf84940185681510395711f2e87198e9d5f94df1b9648f29b3f74be47R114

Works as expected on `0.13.10`. Looks like it's a change in CSTParser.

I couldn't find this information anywhere, sorry if I missed it.

**Comment by domluna** [comment]
This should work with CSTParser 3.2.4

**Comment by domluna** [comment]
fixed with https://github.com/domluna/JuliaFormatter.jl/commit/03b21280e550cbfb1f449fc9f046fc5088117f91

**Comment by domluna** [comment]
working again as of v0.15.3

**Comment by abelsiqueira** [comment]
Thanks!
