### ISSUE TITLE
JuliaFormatter depends on an old PlotlyJS

### ISSUE THREAD

**Issue by ddtarjan** [domluna/JuliaFormatter.jl#442]
Hi,

when I update JuliaFormatter to the newest (to date, it is JuliaFormatter@0.15.1), my PlotlyJS downgrades to 0.13.1, which is quite old.
Similarly - and logically -, if I update PlotlyJS to the latest @0.16.3, JuliaFormatter downgrades to 0.13.10.
Can someone resolve this dependency? Looks too strict, too limiting for me.

**Comment by domluna** [comment]
must be a downstream dependency that's similar? I looked at the Project.toml for PlotlyJS and there's nothing obvious there that could be  the culprit

CSTParser is capped at 2.* for v0.13.*, v0.14.* + uses CSTParser 3.* but I don't know why CSTParser would be used by PlotlyJS

**Comment by ddtarjan** [comment]
Hmm, I'm trying to dig this, but I'm n00b yet in Julia, don't yet have the best tools for dependency tracking.
I recursively checked PlotlyJS' dependencies, but I see no CSTParser there.

Now I removed all other packages, only to keep PlotlyJS and JuliaFormatter.
Let's upgrade PlotlyJS:
```
(@v1.6) pkg> add PlotlyJS@0.16.3
   Resolving package versions...
    Updating `~/.julia/environments/v1.6/Project.toml`
  [f0f68f2c] ↑ PlotlyJS v0.13.1 ⇒ v0.16.3
    Updating `~/.julia/environments/v1.6/Manifest.toml`
  [ad839575] ↑ Blink v0.12.0 ⇒ v0.12.5
  [34da2185] ↑ Compat v2.2.1 ⇒ v3.31.0
  [864edb3b] ↑ DataStructures v0.17.20 ⇒ v0.18.9
  [cd3eb016] ↑ HTTP v0.8.19 ⇒ v0.9.12
  [692b3bcd] + JLLWrappers v1.3.0
  [682c06a0] ↑ JSON v0.20.1 ⇒ v0.21.1
  [50d2b5c4] ↑ Lazy v0.13.2 ⇒ v0.15.1
  [d96e819e] + Parameters v0.12.2
  [69de0a69] + Parsers v1.1.0
  [a03496cd] ↑ PlotlyBase v0.3.1 ⇒ v0.6.4
  [f0f68f2c] ↑ PlotlyJS v0.13.1 ⇒ v0.16.3
  [21216c6a] + Preferences v1.2.2
  [189a3867] ↑ Reexport v0.2.0 ⇒ v1.1.0
  [ae029012] ↑ Requires v0.5.2 ⇒ v1.1.3
  [3a884ed6] + UnPack v1.0.2
  [f7e6163d] + Kaleido_jll v0.1.0+0
```
Now let's upgrade JuliaFormatter:
```
(@v1.6) pkg> add JuliaFormatter@0.15.1
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.6/Project.toml`
  No Changes to `~/.julia/environments/v1.6/Manifest.toml`

(@v1.6) pkg> st
      Status `~/.julia/environments/v1.6/Project.toml`
  [98e50ef6] JuliaFormatter v0.15.1
  [f0f68f2c] PlotlyJS v0.16.3
```
Ohh, then it's not directly PlotlyJS' fault.
But please don't close this ticket yet.
I need those packages.
One of my other packages interfere somehow, I need to find this out.
