### ISSUE TITLE
Use either "in" for "=" when making a for-loop

### ISSUE THREAD

**Issue by KwatME** [domluna/JuliaFormatter.jl#45]
`=` vs `in`
Formatter uses `=` for `for index = 1:n` and uses `in` for `for string in strings`. Should there be only 1 style?

**Comment by domluna** [comment]
See https://github.com/domluna/JuliaFormatter.jl/issues/34.

Sidenote: I need to update the README :-)

**Comment by KwatME** [comment]
Nice.
