### ISSUE TITLE
line break introduced after `@everywhere`

### ISSUE THREAD

**Issue by kafisatz** [domluna/JuliaFormatter.jl#460]
This seems to introduce a linebreak after everywhere which breaks the code
```
format_text("""
using Distributed
@everywhere import Distributed
have_workers = Distributed.nprocs()-1
""", YASStyle(),margin=200)
```

**Comment by domluna** [comment]
So in this context  `@macro import ....` the import to using transform will just not take place.  It's a rare situation so I don't think this is problematic, looking at the julialang repo there are no uses of `@everywhere import ...` they all use `using`.

This may change in the future but for now it's simpler to just avoid this case entirely.
