### ISSUE TITLE
Order types

### ISSUE THREAD

**Issue by KwatME** [domluna/JuliaFormatter.jl#47]
Julia orders types when it prints out the types of an object; for example, `Union{Float64, Nothing}` will be printed out as `Union{Nothing, Float64}`. So there seems to be some internal type orders.

Do you think we can help programmers order their types to match the internal type order of Julia?

<img width="391" alt="Screen Shot 2019-09-01 at 21 28 57" src="https://user-images.githubusercontent.com/7741548/64090339-86b13d00-ccff-11e9-93a4-186414262afd.png">

**Comment by domluna** [comment]
This is a cool idea. I'm not sure how the REPL determines which types to print first, something to investigate.

**Comment by domluna** [comment]
Revisiting this I don't think it's worth pursuing; too much trouble for too little benefit.
