### ISSUE TITLE
pedantic fucntion argument indentation warnings for BlueStyle

### ISSUE THREAD

**Issue by ExpandingMan** [domluna/JuliaFormatter.jl#476]
I don't use this package directly, but I often make PR's to projects which do.  Since I don't use BlueStyle except when I have to, I don't have my editor set up to automatically make code conform to it.  For the most part, this is fine, or at least I feel comfortable taking responsibility for it, because (though I might make mistakes) I can at least see that what I'm writing does not conform to the style.

This is not the case, however, for warnings about function argument indentation, for example, the difference between
```julia
function f(long_argumet_1, long_argument_0)
end
```
and
```julia
function f(
    long_argument_1, long_argument_2
)
end
```

The really infuriating thing happens if, for example, the first above passes, but then I change it to:
```julia

```

**Comment by domluna** [comment]
the last box block looks empty

**Comment by ExpandingMan** [comment]
Oops... embarrassing...

**Comment by ExpandingMan** [comment]
Sorry, I had somehow accidentally continued this in a separate issue... Picard facepalm

**Comment by domluna** [comment]
np I'll close this 1
