### ISSUE TITLE
excessively pedantic argument indentation checks for BlueStyle

### ISSUE THREAD

**Issue by ExpandingMan** [domluna/JuliaFormatter.jl#477]
I don't use this package directly, but I often make PR's to projects which do.  Since I don't use BlueStyle except when I have to, I don't have my editor set up to automatically make code conform to it.  For the most part, this is fine, or at least I feel comfortable taking responsibility for it, because (though I might make mistakes) I can at least see that what I'm writing does not conform to the style.

This is not the case, however, for warnings about function argument indentation, for example, the difference between
```julia
function f(long_argumet_1, long_argument_2)
end
```
and
```julia
function f(
    long_argument_1, long_argument_2
)
end
```

The really infuriating thing happens if, for example, the first above passes, but then I change it to:
```julia
function f(long_argumet_1, long_argument_2::Int)
end
```
now it yells at me because it wants the expanded form.

I understand that when contributing to open source projects we have to conform to conventions we may not agree with because nobody wants a bunch of people coming in and making a mess of their repo, but this case just seems excessive and his burned me about 100 times.

The issue here is that you are pretty much asking people to use a particular editor configuration even to be able to see this problem (as I don't think checking the columns all the time seems reasonable).  Nothing else really does this: for example, I can see the difference between `f(a, b=b)` or `f(a; b=b)`, I can see `return` statements, everything else I can see.  This, you more-or-less need dedicated tools to see.

I'm not completely sure what I'm asking for here since this is obviously extremely specific to this one style supported by this package, but is there a way this can be made a little less stringent so that when somebody does a lint check on a github PR it's not constantly checkign this?

**Comment by domluna** [comment]
I haven't used the GH actions that do these checks so I can't really speak on them.

> The issue here is that you are pretty much asking people to use a particular editor configuration even to be able to see this problem (as I don't think checking the columns all the time seems reasonable). Nothing else really does this: for example, I can see the difference between f(a, b=b) or f(a; b=b), I can see return statements, everything else I can see. This, you more-or-less need dedicated tools to see.

I think one pain point may be the actual style configuration is contained in that github action workflow and not in a .JuliaFormatter.toml file. If the repo has the file then when you format something it should conform to that style automatically and  then you won't have to worry about all the checks on a PR, at least there should be far fewer of them.

**Comment by ExpandingMan** [comment]
Hm.  I guess I feel a bit confused because I'm not too sure what to ask maintainers to do...  I came to this thinking perhaps there is some way of making those checks a little less strict without forcing people to change their maximum number of columns.  For the record, the project where I most recently encountered this simply calls `format(".", BlueStyle, verbose=true)` in the github workflow.  They don't have a `.JuliaFormatter.toml`.

By the way, I had even tried erring on the side of caution and expanding the arguments myself in all but the most obviously non-problematic cases, but this doesn't work either because then it warns you to put it back in compact form.

Sadly as I think some more about this I fear it might be really hard to come up with any solution that makes everyone happy as I'm having an increasingly hard time how we can make this nice without infringing on BluesStyle.

**Comment by domluna** [comment]
> By the way, I had even tried erring on the side of caution and expanding the arguments myself in all but the most obviously non-problematic cases, but this doesn't work either because then it warns you to put it back in compact form.

can you give an example?

**Comment by ExpandingMan** [comment]
You know what, forget it.  This was mostly me expressing my frustrating with both BlueStyle and the entire content of StyleLinters in general :laughing: 

Somewhat embarrasingly, I did not realize until just now that not only does this package produce warnings but it can also rearrange the code for me.  So I'll just use it properly for PR's that require it.  Thanks!

**Comment by domluna** [comment]
np, style wars are a real thing!
