### ISSUE TITLE
@NamedTuple with type parameter

### ISSUE THREAD

**Issue by tpgillam** [domluna/JuliaFormatter.jl#480]
`format_text` will make the following translation. This is fine, and Julia is happy with both forms:

```
@NamedTuple{x::Int, y::Vector{Int}}  # formatter unhappy, Julia happy
@NamedTuple {x::Int, y::Vector{Int}}  # formatter happy, Julia happy
```

However, it also makes the following translation, and in this case the new form doesn't compile:

```
@NamedTuple{x::T, y::Vector{T}} where {T}  # formatter unhappy, Julia happy
@NamedTuple {x::T, y::Vector{T}} where {T}  # formatter happy, Julia unhappy
```

Evaluating the second form (on Julia 1.6.3) gives something like:

```
ERROR: LoadError: ArgumentError: @NamedTuple expects {...} or begin...end
Stacktrace:
 [1] var"@NamedTuple"(__source__::LineNumberNode, __module__::Module, ex::Any)
   @ Base ./namedtuple.jl:387
```

**Comment by domluna** [comment]
I'm wondering whether the formatter shouldn't mess with the whitespace after @macrocall ... at all

right now it'll remove it if there are parenthesis and add a space otherwise

**Comment by tpgillam** [comment]
That might make sense, since removing the space with a parenthesis could change behaviour too — here's a contrived example:

```
julia> @show (1,)
(1,) = (1,)
(1,)

julia> @show(1,)
1 = 1
1
```

**Comment by domluna** [comment]
right so even in the case I thought it made sense to remove the whitespace it can be bad, ok then we won't do that anymore.
