### ISSUE TITLE
3 space alignment after ifs should not be done for BlueStyle

### ISSUE THREAD

**Issue by oxinabox** [domluna/JuliaFormatter.jl#485]
Consider the following code.
It is valid-ish according to BlueStyle.
Valid-ish becuase BlueStyle doesn't make any statement about breaking lines after boolean operators to stay within line limits
So it should be left alone.
```julia
    if primal_name isa Symbol ||
        Meta.isexpr(primal_name, :(.)) ||
        Meta.isexpr(primal_name, :curly)
        
        foo()
    end
```

The output of  JuliaFormatter on the other hand is not right.
    
```julia
julia> format_text(str, BlueStyle()) |> println
if primal_name isa Symbol ||
   Meta.isexpr(primal_name, :(.)) ||
   Meta.isexpr(primal_name, :curly)
    foo()
end
```

It has changed to use 3 spaces to align with the `if`.
BlueStyle *never* does visual alignment, only indenting with 4 spaces.

**Comment by domluna** [comment]
This is because the default style rule is to align it to the arguments in this situation whether that's 3 spaces or something else and blue style fallbacks to that rule atm. So we'll just have to add a blue style specific case

**Comment by domluna** [comment]
Kind of relevant but where does blue style stand on

```
const a =
    arg1 +
    arg2 +
    arg3
```

is it preferred for it to be

```
```
const a = arg1 +
    arg2 +
    arg3
```

I recall somewhere reading that nesting with assignment, like the first code snippet is not preferred.

```
function is_binaryop_nestable(::BlueStyle, cst::CSTParser.EXPR)
    is_assignment(cst) && is_iterable(cst[end]) && return false
    return is_binaryop_nestable(DefaultStyle(), cst)
end
```

currently BlueStyle limits this if the RHS is iterable, such as function call but should this be expanded?
