### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by pfitzseb** [domluna/JuliaFormatter.jl#499]
Looks like docs deployment hasn't worked since 0.16.1.

**Comment by domluna** [comment]
https://github.com/domluna/JuliaFormatter.jl/runs/3998032548?check_suite_focus=true

weird it's linking to v0.16 for some reason

**Comment by Heptazhou** [comment]
This could be closed as fixed by #567.

**Comment by Heptazhou** [comment]
@domluna you might also check out the `Fixing broken release deployments` part [here](https://juliadocs.github.io/Documenter.jl/latest/man/hosting/#Documentation-Versions).
