### ISSUE TITLE
leading zeros for negativ float literals without space

### ISSUE THREAD

**Issue by hexaeder** [domluna/JuliaFormatter.jl#500]
Thanks for the great package! While using I found a small bug i wanted to report:

```julia
a = -.2
b = - .2
```
becomes
```julia
a = -.2
b = -0.2
```
which is inconsistent.

Well personally I'd rather prefer to allow the concise `.2` and `1.` syntax in general but adding another option for that might be to much to ask for 😬

**Comment by domluna** [comment]
the leading 0 is added on purpose but it looks like '-0.2' has '-' as part of the float value where I think in CSTParser 2 it might not have been. So the leading 0 not being added on the first line is a bug, but the leading 0 being added generally to `.x` and `x.` expressions is not.
