### ISSUE TITLE
Optionally disable enforcement of trailing zeros in float literals

### ISSUE THREAD

**Issue by serenity4** [domluna/JuliaFormatter.jl#517]
Having trailing zeros in floats is mostly a matter of style, and would IMHO fit very well as a parameter to be configured in a `.JuliaFormatter.toml`. If there is any chance to expose it, it would be very much appreciated!

**Comment by domluna** [comment]
I think something similar to the trailing_comma option could work. You could also get very granular and have one option for leading 0s and one for trailing 0s
