### ISSUE TITLE
Expose option for wrapping `where` clauses with curly brackets

### ISSUE THREAD

**Issue by serenity4** [domluna/JuliaFormatter.jl#522]
Some people tend to prefer not using curly brackets in `where` clauses, such as
```julia
function f(x::T) where T
  do_something(x)
end
```

where the first line is formatted into `function f(x::T) where {T}` automatically. I think it would be an improvement (albeit minor) to expose this as an option such that for single parameter `where` clauses the user can decide whether or not to put curly brackets. Of course, with more than one argument to `where`, then curly brackets are required.

**Comment by domluna** [comment]
fixed by `surround_whereop_typeparameters` option
