### ISSUE TITLE
where {T} vs where T

### ISSUE THREAD

**Issue by odow** [domluna/JuliaFormatter.jl#53]
Following https://github.com/jrevels/YASGuide#other-syntax-guidelines, I propose that all occurrences of `where T` are replaced with `where {T}`. 

This makes things clearer, and unifies the syntax with more complicated `where` statements (e.g., with multiple terms) which require `{}`.

Bad:
```Julia
function foo(x::T) where T <: Integer
    return 2x
end
```

Good:
```Julia
function foo(x::T) where {T <: Integer}
    return 2x
end
```

p.s. very cool. Thanks for working on this.

Edit: to make the point more explicit:

Also Bad:
```Julia
function foo(x::T) where T
    return 2x
end

bar(x::T) where T = 2x
```

Good:
```Julia
function foo(x::T) where {T}
    return 2x
end

bar(x::T) where {T} = 2x
```

**Comment by StefanKarpinski** [comment]
What about `where T` but `where {T <: Integer}`. There is a slight wrinkle that people prefer the `{ }` version in the one-line case:
```jl
foo(x::T) where T = 2x # confusing
foo(x::T) where {T} = 2x # clearer
```
So a possible rule would be this:
- no braces in long form function definition when the where clause is just a single typevar
- otherwise always enclose in braces

**Comment by odow** [comment]
The fewer special exceptions the better. 

For the sake of two characters, instead of having to remember (and code, maintain, etc) _if_ long form _and_ single type var, it's just "Always enclose in braces."

**Comment by domluna** [comment]
Added this in 8944eaad622b8b88fa8b0f1d9e0dd7ef506fc742
