### ISSUE TITLE
The semicolons in multi-dimensional array syntax (new in 1.7) are incorrectly deleted inside a name tuple [Blue style]

### ISSUE THREAD

**Issue by MrVPlusOne** [domluna/JuliaFormatter.jl#532]
Hi, I'm using the blue style, and the following code 
```julia
(; a=[1;;], b=cos[2;;])
```
gets formatted into 
```julia
(; a=[1;], b=cos[2;;])
```
which changes the shape of the first array.

This bug does not appear if I rewrite the named tuple using the other syntax (i.e., without the leading semicolon):
```julia
(a=[1;;], b=cos[2;;])
```

**Comment by domluna** [comment]
This is a hard edge case for the current way the semicolon stuff is done. CSTParser doesn't track these which makes it difficult. I think the best solution is to make CSTParser stores the semicolons in the `meta` or `trivia` fields of a CSTParser.EXPR but I have to run that by those folks first.

**Comment by eschnett** [comment]
A similar error occurs with the `yas` style, independent of the new 1.7 syntax. The expression
`[[1, 2];]`
is converted into
`[[1, 2]]`
which is a very different object. The first is a `Vector{Int}`, the second a `Vector{Vector{Int}}`.

**Comment by domluna** [comment]
> A similar error occurs with the yas style, independent of the new 1.7 syntax. The expression
[[1, 2];]
is converted into
[[1, 2]]
which is a very different object. The first is a Vector{Int}, the second a Vector{Vector{Int}}.

This is fixed on the latest release
