### ISSUE TITLE
Trailing comma is inserted even when there is a trailing semicolon

### ISSUE THREAD

**Issue by johannes-fischer** [domluna/JuliaFormatter.jl#538]
With
```
trailing_comma = true
join_lines_based_on_source = true
```
This perfectly valid code
```
f(a; b=1) = a + b

f(
    1;
)
```
is formatted to
```
f(a; b=1) = a + b

f(
    1;,
)
```
which raises a syntax error due to the unexpected ",".

It's not a big issue and can be easily resolved by removing the semicolon, but I thought I'd still report it.

Thanks for the package, I've just discovered it!

**Comment by domluna** [comment]
What version is this? I don't seem to have this issue on the latest release

**Comment by johannes-fischer** [comment]
Ah then nevermind, I was using VS code Julia extension. Sorry, should have checked with the package itself.
