### ISSUE TITLE
`align_matrix` adds spurious whitespace

### ISSUE THREAD

**Issue by goerz** [domluna/JuliaFormatter.jl#543]
The `align_matrix` option adds spurious whitespace when applied to a matrix defined with a semicolon:

```julia
julia> using JuliaFormatter
julia> format_text("H= [0  0.5; 0.5 0]", align_matrix=true)
"H = [0  0.5;         0.5 0]"
```

**Comment by goerz** [comment]
A further example: A file
~~~julia
H = [1 1; 1 1]
Zero = [0 0; 0 0]

G1 = vcat(hcat(H,    Zero, H),
          hcat(Zero, H,    H),
          hcat(Zero, Zero, H))

G2 = [ H    Zero  H;
      Zero    H   H
      Zero  Zero  H]

G3 = [ H    Zero  H;
      Zero    H   H
      Zero  Zero  H]

G4 = [ H    Zero  H; Zero    H   H
      Zero  Zero  H]
~~~

comes out as

```julia
H = [1 1;      1 1]
Zero = [0 0;      0 0]

G1 = vcat(hcat(H, Zero, H), hcat(Zero, H, H), hcat(Zero, Zero, H))

G2 = [
     H    Zero  H
    Zero    H   H
    Zero  Zero  H
]

G3 = [
     H    Zero  H
    Zero    H   H
    Zero  Zero  H
]

G4 = [
     H    Zero  H
                   Zero    H   H
    Zero  Zero  H
]
```

`G1`–`G3` are totally fine, but `G4` is not. Granted, `G4` is a very pathological example, and I'm not even sure how it *should* be autoformatted. Probably

```julia
G4 = [
     H    Zero  H; Zero    H   H
    Zero  Zero  H
]
```

**Comment by domluna** [comment]
it looks like the problem occurs when there are >= 2 rows on a single line in the original code.

not sure what the fix should be since the whole idea is 1 row per line for alignment to work properly. Maybe it should be to break up the rows?

hmmm

**Comment by goerz** [comment]
I may not have fully thought this through, but I'd be inclined to say if there are multiple rows in a single line (if there's a `;` present?) just leave it as-is, up to indentation of the entire line.

Of course, nobody should ever write code like the original `G4` and it would be fair to demand that they rewrite it manually (so the output of `format` doesn't really matter that much). The single-line `H = [1 1; 1 1]` on the other hand is pretty reasonable, and should definitely stay as-is, IMO.
