### ISSUE TITLE
Alignment of comments inside `begin` blocks

### ISSUE THREAD

**Issue by odow** [domluna/JuliaFormatter.jl#55]
I took a pass over my SDDP.jl library (https://github.com/odow/SDDP.jl/pull/256) and for the most part, it worked great! SDDP.jl should be a reasonably good test-case because it includes quite a few JuMP models with weird macro syntax.

Here's one of the things that came out of it:
```Julia
using JuliaFormatter

s = """
@foo(a, begin
    # A comment
    a_very_long_line_with_just_more_than_80_characters + a_very_long_line_with_just_
end)
"""

print(JuliaFormatter.format_text(s))

# outputs

@foo(
    a,
    begin
    # A comment
        a_very_long_line_with_just_more_than_80_characters + a_very_long_line_with_just_
    end
)

# expected (I): align comments inside a re-formatted block

@foo(
    a,
    begin
        # A comment
        a_very_long_line_with_just_more_than_80_characters + a_very_long_line_with_just_
    end
)

# expected (II): begin blocks that are the last argument behave differently

@foo(a, begin
    # A comment
    a_very_long_line_with_just_more_than_80_characters + a_very_long_line_with_just_
end)
```

**Comment by domluna** [comment]
Previously there was an attempt at aligning comments but it didn't always produce the desired output, there are some wacky edge cases. Formatting comments is tricky business! At the moment I'm going to opt for this to be done manually, since you would only really have do this the first time something is formatted anyway.

**Comment by odow** [comment]
Fine by me! We can always re-visit at a later date; I understand the engineering challenge in the near-term.
