### ISSUE TITLE
VS Code formatting issues

### ISSUE THREAD

**Issue by davidanthoff** [domluna/JuliaFormatter.jl#558]
I migrated the whole package butler ecosystem over to JuliaFormatter.jl now, and if I got it right then it should use the same settings that are the default in the VS Code extension. I'm currently looking through various repos where the formatter is now being applied, and as I find issues that I think we still need to address, I'll link them here. But overall, this is all looking really great!

- [ ] https://github.com/julia-vscode/JSONRPC.jl/pull/61/files#r825259279
- [ ] https://github.com/julia-vscode/JSONRPC.jl/pull/61/files#r825259330
- [ ] https://github.com/julia-vscode/SymbolServer.jl/pull/248/files#r825259549
- [ ] https://github.com/julia-vscode/SymbolServer.jl/pull/248/files#r825259761
- [ ] https://github.com/julia-vscode/SymbolServer.jl/pull/248/files#r825260400
- [ ] https://github.com/julia-vscode/SymbolServer.jl/pull/248/files#r825260479
- [ ] https://github.com/julia-vscode/SymbolServer.jl/pull/248/files#r825260666
- [ ] https://github.com/julia-vscode/DebugAdapter.jl/pull/54/files#r825260718
- [ ] https://github.com/julia-vscode/DebugAdapter.jl/pull/54/files#r825260780

CC @pfitzseb

**Comment by davidanthoff** [comment]
Bump, how can we make progress on this?

**Comment by davidanthoff** [comment]
@domluna Bump, do you have a sense how we could make progress on this?

**Comment by domluna** [comment]
hello! Probably open up individual issues so we can track it. Most of these shouldn't be too bad.

**Comment by domluna** [comment]
https://github.com/domluna/JuliaFormatter.jl/issues/561 would be the hardest aspect of this

**Comment by davidanthoff** [comment]
Alright, I moved all of these out into individual issues, so closing this meta issue here.
