### ISSUE TITLE
Allow format of .qmd files in addition to .jmd

### ISSUE THREAD

**Issue by dmbates** [domluna/JuliaFormatter.jl#569]
https://quarto.org/ provides for technical writing with evaluation of code blocks in Python, R, Julia and Observable.  It is a comprehensive and flexible system.  The source files carry a .qmd extension.  I can format the Julia code by moving the file to a .jmd extension, formatting that file and moving back to a .qmd extension but it would be cleaner to just allow the .qmd extension.  I am happy to create a PR if this seems like a good idea.

**Comment by dmbates** [comment]
I am trying to find out where a Julia code block in the text is detected.  In a Quarto .qmd file an executable Julia code blocks starts with three backticks and `{julia}` (not sure how to write that in a markdown message).  It appears that if I remove the braces around `julia` the code block is recognized, but the braces are necessary for the Quarto file to be processed correctly.

**Comment by domluna** [comment]
it's pretty well hidden, should be in the markdown.jl file but this line https://github.com/domluna/JuliaFormatter.jl/blob/master/src/styles/default/pretty.jl#L241 is what you're looking for.

Now the markdown parser is based on https://github.com/MichaelHatherly/CommonMark.jl and I'm unsure how well it supports .qmd files
