### ISSUE TITLE
ERROR: UndefVarError: get_where_params not defined

### ISSUE THREAD

**Issue by s-baumann** [domluna/JuliaFormatter.jl#585]
I am getting the error:

```
julia> format("src//00_sorteddataframe.jl")
ERROR: UndefVarError: get_where_params not defined
Stacktrace:
 [1] p_whereopcall(ds::DefaultStyle, cst::CSTParser.EXPR, s::JuliaFormatter.State)
   @ JuliaFormatter C:\Users\dr\.julia\packages\JuliaFormatter\gUMR4\src\pretty.jl:1238
```

THis is when I try to format the file here:
https://github.com/s-baumann/HighFrequencyCovariance.jl/blob/main/src/00_SortedDataFrame.jl
I get the same thing when trying to reformat
https://github.com/s-baumann/HighFrequencyCovariance.jl/blob/main/src/30_Regularisation_identity.jl

**Comment by s-baumann** [comment]
Doing some testing this comes from the where clause. So this will make it fail
```
function func(A::R) where R<:Real
    return A
end
```
This is fine:
```
function func(A::Real)
    return A
end
```

**Comment by domluna** [comment]
I don't get this on error on 1.0.0 are you formatting with different options (non-defaults)?

**Comment by s-baumann** [comment]
I am not doing any non-defaults. 

A MWE for me is:
```
using JuliaFormatter
format("bug_MWE.jl")
```
where bug_MWE is a file in the working directory containing:
```
function f(x::R) where R<:Real
    return x + 1
end
```

I am running Julia 1.7.2 with 
```
 [98e50ef6] JuliaFormatter v0.3.7
  [00ebfdb7] CSTParser v2.5.0
```

**Comment by domluna** [comment]
you gotta upgrade to the most recent release then you won't have  this issue
