### ISSUE TITLE
Non-trailing semicolons disappearing with YAS

### ISSUE THREAD

**Issue by jbrightuniverse** [domluna/JuliaFormatter.jl#608]
`hcat([zeros(1); ones(3)], [zeros(2); ones(2)], [zeros(3); ones(1)], [zeros(1); ones(3)], [zeros(2); ones(2)], [zeros(3); ones(1)])` evaluates to:
```
4×6 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  1.0  0.0  0.0
 1.0  1.0  0.0  1.0  1.0  0.0
 1.0  1.0  1.0  1.0  1.0  1.0
```
The code:
```
format_text("hcat([zeros(1); ones(3)], [zeros(2); ones(2)], [zeros(3); ones(1)], [zeros(1); ones(3)], [zeros(2); ones(2)], [zeros(3); ones(1)])", style = YASStyle())
```
returns the following string (with newline):
```
hcat([zeros(1); ones(3)], [zeros(2); ones(2)], [zeros(3); ones(1)], [zeros(1) ones(3)],
     [zeros(2) ones(2)], [zeros(3) ones(1)])
```
This raises a dimension mismatch error when run as code in a file because several semicolons are dropped, which alters the structure of the matrices.

**Comment by domluna** [comment]
fixed with #623
