### ISSUE TITLE
inline comments in function calls removed for SciMLStyle

### ISSUE THREAD

**Issue by visr** [domluna/JuliaFormatter.jl#609]
```julia
t = """
# https://github.com/SciML/SciMLStyle#comments
# In general, comments above a line of code or function are preferred to inline comments.
f(; q) = q
f(
    q = 2  # this comment will be removed
)
"""

format_text(t, style=SciMLStyle()) |> Text
```

Returns
```julia
# https://github.com/SciML/SciMLStyle#comments
# In general, comments above a line of code or function are preferred to inline comments.
f(; q) = q
f(q = 2)
```

As noted the style guide favors commands above, but I assume the formatter is not supposed to remove them?
#513 and #562 seem similar, but not the same.

For the example of #513 only the last comment gets removed:

```julia
f(10 # i got removed!
  *
  10 # me too!
  +
  10)
```

**Comment by domluna** [comment]
interesting corner case since SciMLStyle uses YASStyle for a lot of defaults and YASStyle doesn't allow opening/closing parenthesis to be on their own line.

The simplest fix which should still adhere to the style is to put the comment after the closing parenthesis

**Comment by visr** [comment]
This seems to be fixed, now the input string is kept as-is.
