### ISSUE TITLE
Utilize as much row space as possible for array

### ISSUE THREAD

**Issue by HaoxuanGuo** [domluna/JuliaFormatter.jl#612]
When an array exceeds the row limit, it is formatted to look like one element per row.

```Julia
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
```

will be formatted to

```Julia
a = [
    1,
    2,
    ...
    30,
]
```

In C/C++ formatter, there is an another option is 

```C++
int a[] = {1,  2,  3,  4,  5,  6,  7,  8,  9,  10, 11, 12, 13, 14, 15,
           16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30}
```

Use as much full row space as possible and keep elements aligned between columns.

Is it possible to implement this formatting method?

**Comment by domluna** [comment]
you can use join_lines_based_on_source = true which will line break based on the original source code but it will still adhere to margin limits.

**Comment by HaoxuanGuo** [comment]
That is a little different with `join_lines_based_on_source`. That will try to keep the original feed but may not try to use as much full line space (keep as much as less lines).

The final result may be close but the original intention is not the same. Does this line feed make sense?

**Comment by domluna** [comment]
It does make sense but it's just how the style you're using works.
