### ISSUE TITLE
trailing_comma = nothing seems not to work

### ISSUE THREAD

**Issue by davidanthoff** [domluna/JuliaFormatter.jl#624]
[This](https://github.com/julia-vscode/CSTParser.jl/pull/353/files) is the result of running JuliaFormatter v1.0.7 with the minimal style.

It looks like it is changing things like
```julia
deploydocs(;
    repo="github.com/julia-vscode/CSTParser.jl",
)
```
to
```julia
deploydocs(;
    repo="github.com/julia-vscode/CSTParser.jl"
)
```
Note how it is removing the comma on the second line. I would expect the `trailing_comma = nothing` option to mean to just leave commas alone, right?

**Comment by domluna** [comment]
special case when keyword args are present
