### ISSUE TITLE
Inconsistent formatting of expressions within a matrix - trouble with `format` versus `format_file`

### ISSUE THREAD

**Issue by dawbarton** [domluna/JuliaFormatter.jl#626]
I've written quite a bit of code that involves lengthy algebraic expressions inside matrices; for some reason the formatting of the expressions is somewhat inconsistent. For example

```julia
# Original
K = @SMatrix [
    k_h 2π*ρ*b*U^2*(c₀-c₁-c₃)               2π*ρ*U^3*c₂*c₄*(c₁+c₃)
    0   k_α-2π*(1/2+a)*ρ*(c₀-c₁-c₃)*b^2*U^2 -2π*ρ*b*U^3*(a+1/2)*c₂*c₄*(c₁+c₃)
    0   -U/b                                c₂*c₄*U^2/b^2
]

# Formatted with `format` (blue-style)
K = @SMatrix [
    k_h 2π*ρ*b*U^2*(c₀ - c₁-c₃) 2π*ρ*U^3*c₂*c₄*(c₁+c₃)
    0 k_α-2π * (1 / 2 + a) * ρ * (c₀ - c₁ - c₃) * b^2 * U^2 -2π*ρ*b*U^3*(a+1 / 2)*c₂*c₄*(c₁+c₃)
    0 -U/b c₂ * c₄ * U^2/b^2
]

# Formatted with `format_file` (blue-style)
K = @SMatrix [
    k_h 2π*ρ*b*U^2*(c₀-c₁-c₃) 2π*ρ*U^3*c₂*c₄*(c₁+c₃)
    0 k_α-2π*(1/2+a)*ρ*(c₀-c₁-c₃)*b^2*U^2 -2π*ρ*b*U^3*(a+1/2)*c₂*c₄*(c₁+c₃)
    0 -U/b c₂*c₄*U^2/b^2
]
```

I'm not sure why some of the operators get spaces around them and others don't. Is this expected?

Edit: this is with JuliaFormatter v1.0.7 and Julia v1.8.0-rc3

**Comment by domluna** [comment]
format_file doesn't check for .JuliaFormatter.toml so that might be why the output is different. If you call `format` on that file specifically then it should pick up the custom config from .JuliaFormatter.toml

I think `format_file` as it is should be unexported and rewritten to `_format_file` and then have a `format_file` function which just calls `format`. This came up in another issue I think.

**Comment by domluna** [comment]
when you are calling format_text what arguments are you passing in?

**Comment by dawbarton** [comment]
That would explain the differences between `format` and `format_file`. Thanks for the explanation. If agree that unexporting `format_file` sounds sensible.

It still leaves the question of why sometimes there are spaces around operators and sometimes not. Take the multiplications for example - sometimes they are spaced out and sometimes not with the only real difference being that they are on different lines.

**Comment by domluna** [comment]
> It still leaves the question of why sometimes there are spaces around operators and sometimes not. Take the multiplications for example - sometimes they are spaced out and sometimes not with the only real difference being that they are on different lines.

I'll look into that although I think it might be a blue vs default style thing
