### ISSUE TITLE
broadcasted piping is broken?

### ISSUE THREAD

**Issue by rafaqz** [domluna/JuliaFormatter.jl#636]
In DiskArrays.jl JuliaFormatter.jl (using BlueStyle) produced this line:

```julia
coordsperm = x -> x.I[[2, 1, 3]] |> CartesianIndex(coords)
```

From this source:
```julia
  coordsperm = coords .|> x -> x.I[[2, 1, 3]] |> CartesianIndex
```

See: https://github.com/meggart/DiskArrays.jl/commit/1ed9b473ce7f3473b0b1ec73413cd74839ac88ad#r80884442

**Comment by Satvik** [comment]
This got us too. A minimal version: `format_text("a |> M.f"; pipe_to_function_call=true)` returns `"M.f.(a)"`

**Comment by domluna** [comment]
ok got this pretty much working but something to be mindful of is that -> has higher precedence than |>, meaning the above would wrap be formatted as

```
coordsperm = (x -> x.I[[2, 1, 3]] |> CartesianIndex).(coords)

```

If you wrap the anon func in parenthesis then the format will be different

```
coordsperm = CartesianIndex((x -> x.I[[2, 1, 3]]).(coords))
```
