### ISSUE TITLE
Log which file is being formatted when failure occurs

### ISSUE THREAD

**Issue by charleskawczynski** [domluna/JuliaFormatter.jl#640]
`format(filename; kwargs...)` often gives unhelpful error messages, and that very well may be the best and safest thing to do because we perhaps can't reason about code without trying to compile it.

However, `format(path; kwargs...)` gives unhelpful results, and 99% of the time I spend a few minutes applying `format` to all the Julia files I see in `git diff main` on a development branch. Or worse (e.g., for the very first time in a new repo) file by file. I think many people, including myself, would find it useful if we were to wrap `format` in a try-catch so that we can still throw the same error but also print out which file is failing to format.

I'm not super familiar with JuliaFormatter.jl but, concretely, I want a function like this:

```julia
function logged_format(paths; kwargs...)
    jl_files = map(paths) do path
        [
            joinpath(root, f) for
            (root, dirs, files) in Base.Filesystem.walkdir(path) for
            f in files if endswith(f, ".jl")
        ]
    end
    for f in Iterators.flatten(jl_files)
        try
            format(f; kwargs...)
        catch # still error, but tell us which file this happened in
            @error "Error in formatting file $f" # could also be `@warn` or `@info`
            format(f; kwargs...)
        end
    end
end
```

**Comment by domluna** [comment]
would wrapping

https://github.com/domluna/JuliaFormatter.jl/blob/master/src/JuliaFormatter.jl#L864
https://github.com/domluna/JuliaFormatter.jl/blob/master/src/JuliaFormatter.jl#L847

in a try catch block do this?
