### ISSUE TITLE
Unable to format Julia code in markdown files

### ISSUE THREAD

**Issue by TorkelE** [domluna/JuliaFormatter.jl#654]
I am trying to format some additional docs for on of the SciML packages (https://github.com/SciML/Catalyst.jl/pull/565), however, I cannot get it to work. In the end, I have managed to narrow it down to me not being able to format .md files. Here follows an example:

I create two very similar files, a .jl file, and a .md file with the julia code in a block. The code is take from the JuliaFormatter docs.
![image](https://user-images.githubusercontent.com/18099310/201151998-7373f8d3-a5a9-4a88-93d9-86bc978f631e.png)

I then try to format the .jl file using `format("testfile.jl";remove_extra_newlines=true)` this successfully formats the .jl file:
![image](https://user-images.githubusercontent.com/18099310/201152274-f579be00-92c5-47e6-801c-05e1e4447273.png)

Next, I try to format the .md file using `format("testfile.md";remove_extra_newlines=true)`, however, this seems to have no effect:
![image](https://user-images.githubusercontent.com/18099310/201152776-31d7406c-b8a7-41f6-904c-e11ac3bb5a73.png)
and I am not sure how to get this working.

**Comment by domluna** [comment]
`format("testfile.md";remove_extra_newlines=true, format_markdown=true)`

**Comment by TorkelE** [comment]
This worked, thanks a lot :)
