### ISSUE TITLE
indentation for empty lines

### ISSUE THREAD

**Issue by cmichelenstrofer** [domluna/JuliaFormatter.jl#667]
The formatter adds indentation to empty lines before an indented line. 
This is problematic because many people (myself) have our editor strip trailing white spaces, so there is always a conflict. Here is an example in a docstring:

![Screenshot 2022-12-18 23 39 25](https://user-images.githubusercontent.com/25060182/208363445-8f9641d2-172c-4752-9717-fe46135cbd92.png)

**Comment by domluna** [comment]
can you post the snippet

**Comment by cmichelenstrofer** [comment]
Here's the snippet: 

```julia
"""
    𝐀

A dimension representing Angle.

!!! note "Not SI"

    *Angle* is not an SI base dimension.
"""
@dimension 𝐀 "𝐀" Angle true
```

From [this file](https://github.com/cmichelenstrofer/DimensionfulAngles.jl/blob/main/src/DimensionfulAngles.jl#L47).
