### ISSUE TITLE
Multiple semicolons not recognized and removed

### ISSUE THREAD

**Issue by chrisn-pik** [domluna/JuliaFormatter.jl#670]
When using multi-dimensional array literals, e.g. 
```julia
d = [a;;; b;;; c;;;]
```
formating results in:
```julia
d = [a; b; c]
```

**Comment by domluna** [comment]
```
julia> using JuliaFormatter
[ Info: Precompiling JuliaFormatter [98e50ef6-434e-11e9-1051-2b60c6c9e899]

julia> s = """
       d = [a;;; b;;; c;;;]
       """
"d = [a;;; b;;; c;;;]\n"

julia> format_text(s) |> print
d = [a;;; b;;; c]

(JuliaFormatter) pkg> st
Project JuliaFormatter v1.0.17
Status `~/.julia/dev/JuliaFormatter/Project.toml`
  [00ebfdb7] CSTParser v3.3.6
⌃ [a80b9123] CommonMark v0.8.6
  [864edb3b] DataStructures v0.18.13
  [c27321d9] Glob v1.3.0
⌃ [0796e94c] Tokenize v0.5.24
  [44cfe95a] Pkg v1.8.0
```

you're probably on an older version before the syntax for this was supported

**Comment by chrisn-pik** [comment]
I am using Codium with the extension Julia Formatter v0.6.3 and the Julia package  JuliaFormatter v0.13.7 and tried the following:

```julia
d1 = [a;; b;; c]
s = """
d2 = [a;;; b;;; c;;;]
"""
```
d1 is modified and d2 stays the same, so perhaps the syntax is recognized within the string. The reason might be Codium or the extension.

**Comment by domluna** [comment]
yeah it looks like it's using an outdated version of JuliaFormatter
