### ISSUE TITLE
Format `Dict` definitions like `Vector` definitions

### ISSUE THREAD

**Issue by efaulhaber** [domluna/JuliaFormatter.jl#675]
We're using the SciML style guide since we found that it's very consistent with our "in-house" style.
However, we would like to format `Dict` definitions similar to `Vector` definitions like this:
```julia
x = [
    "some arbitrary string bla bla bla bla bla bla bla bla bla",
    "another longer arbitrary string bla bla bla bla bla bla bla bla",
]

SomeLongerTypeThanJustString = String
y = Dict{Int, SomeLongerTypeThanJustString}(
    1 => "some arbitrary string bla bla bla bla bla bla bla bla bla",
    2 => "another longer arbitrary string bla bla bla bla bla bla bla bla"
)
```
After auto-formatting, however, it looks like this:
```julia
y = Dict{Int, SomeLongerTypeThanJustString}(1 => "some arbitrary string bla bla bla bla bla bla bla bla bla",
                                            2 => "another longer arbitrary string bla bla bla bla bla bla bla bla")
```
This also goes way beyond the 92-character limit.
Is there a way to redefine this behavior without changing the rest of the formatting rules?

**Comment by efaulhaber** [comment]
Thanks! The array call is already formatted the way I want it to. I just want to format `Dict` calls according to `DefaultStyle`.

From my understanding, before I even try to figure out how to check if the caller is a `Dict`, just redefining
```julia
function JuliaFormatter.p_call(style::SciMLStyle, cst::CSTParser.EXPR, s::JuliaFormatter.State)
    JuliaFormatter.p_call(DefaultStyle(style), cst, s)
end
```
should already format the `Dict` definition the way I want to, right? But it would then also change the formatting of function calls, which I don't want to do.

However, after this redefinition, I now end up with this:
```julia
y = Dict{Int, SomeLongerTypeThanJustString}(
                                            1 => "some arbitrary string bla bla bla bla bla bla bla bla bla",
                                            2 => "another longer arbitrary string bla bla bla bla bla bla bla bla"
                                            )
```
So, one additional line break after the opening parenthesis, but still with the indent that I don't want.

**Comment by domluna** [comment]
yes that should work!

oh sorry you'll also have to update the nesting function as well since that determines how it's indented, etc. n_call! - here's an example https://github.com/domluna/JuliaFormatter.jl/blob/master/src/styles/yas/nest.jl#L1

**Comment by domluna** [comment]
but that will work for function calls not just ones with Dict, maybe that's what you want but if not you would need to verify the caller is Dict.

**Comment by efaulhaber** [comment]
Thanks, now that part works.
How can I verify that the caller is `Dict`?

**Comment by domluna** [comment]
cst[1] will be that node. It seems either it's a curly node or a leaf node

JuliaFormatter.is_leaf(cst[1])

will check this

so you can do

```
is_dict_call = false
if JuliaFormatter.is_leaf(cst[1]) && cst[1].val == "Dict"
  is_dict_call = true
elseif !JuliaFormatter.is_leaf(cst[1]) && JuliaFormatter.is_leaf(cst[1][1]) && cst[1][1].val == "Dict"
  is_dict_call = true
end
   
```

then dispatch based on is_dict_call

**Comment by domluna** [comment]
and then do something similar for n_call!

**Comment by efaulhaber** [comment]
Thank you very much! Everything works as expected. Only forwarding all functions to `SciMLStyle` was a bit of a hassle.

Now, is there any way to use my custom style in VS Code? It seems like the config only allows the predefined styles:
https://github.com/domluna/JuliaFormatter.jl/blob/9092f298f95d9562521ee36c54bf82892753e238/src/JuliaFormatter.jl#L939-L946

**Comment by domluna** [comment]
you could make a PR for the new style and then we can set an option for it
in the config file
