### ISSUE TITLE
"no indent rule" also for other blocks than modules

### ISSUE THREAD

**Issue by ranocha** [domluna/JuliaFormatter.jl#707]
Would it be possible to have a no-indent-rule also for other top level blocks besides `module`s?

Our use case in Trixi.jl is something like this

```julia
@muladd begin

# lots of stuff

end # @muladd
```

A lot of our files look like this. Thus, JuliaFormatter.jl basically indents all of our files - which we would like to avoid.

CC @sloede 
Xref https://github.com/trixi-framework/Trixi.jl/pull/1403#issuecomment-1514697345

**Comment by domluna** [comment]
https://github.com/domluna/JuliaFormatter.jl/pull/724
