### ISSUE TITLE
Always surround tuples with parenthesis

### ISSUE THREAD

**Issue by domluna** [domluna/JuliaFormatter.jl#71]
Julia supports tuples being written as

1.

```julia
julia> a = 1,2,3
(1, 2, 3)
```

2.

```julia
julia> a = (1,2,3)
(1, 2, 3)
```

I propose we always transform 1 to 2

**Comment by StefanKarpinski** [comment]
People do like to write `a, b = b, a`. Would you transform that to `(a, b) = (b, a)`?

**Comment by domluna** [comment]
Hmmm maybe `a, b = (b, a)` ? tuples after `return` would be another case but I think those look better with parens:

`return (a, b)` vs `return a, b`

I don't want this to be something with several cases where we choose not to surround with parens, so if that's the case it's better not to do this change and leave things to the programmer IMO.

**Comment by odow** [comment]
:+1: for everywhere and one less special case. 
```Julia
a = (1, 2)
(a, b) = (b, a)
return (a, b)
```
When writing, people can choose whatever, and the formatter will correct them.

**Comment by StefanKarpinski** [comment]
There are other situations where parens may make things less clear, for example:

* `@m a, b` vs
* `@m (a, b)` vs
* `@m(a, b)` vs
* `@m a b`.

Hint: the first and last pair mean the same thing, even though the middle and outer two look alike. Also note that after the `do` keyword the parens are significant:

* `do a, b` vs
* `do (a, b)`

mean different things.

**Comment by StefanKarpinski** [comment]
At a higher level, I worry about the philosophy of always minimizing special cases. I get it, it's simpler to implement and easier to explain what the rules are, but I think it will make people _much_ more reluctant to use the formatter. The simplest, most consistent formatter possible would produce code that's barely human readable, so clearly going fully in that direction is clearly not desirable. A lot of effort has been put into `gofmt` to make it produce code which people don't find too unpleasant to look at even if they don't love all of its policies. If this tool is going to have a chance to be widely accepted, I think it needs to produce formatted code that people don't find too unpleasant and doesn't deviate too much from what they like to write and read. To accomplish that, one needs to look at how people actually use the syntax that's available.

I do not, for example, think that people generally put parens around tuples used for destructuring. They also do not generally use parens around multiple return values. Maybe it's fine to reformat those uses to put parens in, but I think that if JuliaFormatter starts to favor consistency and simplicity above all else, regardless of what people do, without at least looking at it and considering what people like to write, it will severely hamper adoption. Would you want to use a tool that reformats your code in a way that you find really unpleasant? I certainly wouldn't. I'm not saying that we should not consistently put parens around tuples—maybe we should—but I think that the attitude of just decreeing things based on simplicity and consistency is an existential danger to this project.

**Comment by StefanKarpinski** [comment]
Or more succinctly, please look at actual usage before deciding if it's ok to put parens everywhere.

**Comment by domluna** [comment]
This was more of a thought experiment than anything else. I feel at this point I think there's an implicit "Stefan let me know if this is actually a good idea based on real usage" 😉 

I wholeheartedly agree any change of this kind going forward should be based on how folks are actually using the language. A very important difference between this and `gofmt` is `gofmt` was available right at the start, so it dictated how people wrote code. I believe Julia is on the other end of the spectrum and it's important to be mindful of that.

**Comment by odow** [comment]
>  I think that the attitude of just decreeing things based on simplicity and consistency is an existential danger to this project.

Fair point. Echoing [@mlubins comment](https://github.com/domluna/JuliaFormatter.jl/pull/70#issuecomment-532920949), I'm happy for you/@domluna to pull rank and choose one of the options and make it a rule. Here and in all future decisions.

**Comment by domluna** [comment]
Ok this one was pretty poorly thought out, even as a thought experiment, that's my fault. Taking a closer look there's too many cases where no parens would have a different meaning or just be aesthetically preferable to parens.

Additionally at this point we're getting "stableish" and should focus on fixing lingering bugs and weird format cases rather than making these kind of transformational changes.
