### ISSUE TITLE
Avoid indentation within `@testitem` blocks

### ISSUE THREAD

**Issue by gdalle** [domluna/JuliaFormatter.jl#711]
The new [test item framework](https://discourse.julialang.org/t/prerelease-of-new-testing-framework-and-test-run-ui-in-vs-code/86355) in VSCode allows you to specify standalone tests that can be executed independently. However, since they are typically pretty long, it would be nice to avoid indenting them (as is done eg. for `module` blocks). What do you think? Is that a difficult change?

**Comment by domluna** [comment]
Probably similar effort to https://github.com/domluna/JuliaFormatter.jl/pull/489/files

**Comment by domluna** [comment]
similar to https://github.com/domluna/JuliaFormatter.jl/issues/707

generalizing the module indent option to user patterns might be worth it

**Comment by domluna** [comment]
maybe adding a comment so something along the lines of

```
@muladd begin
# fmt: dedent
code here is not indented
end
```

i think this should be fairly easy to add since in print.jl you can check if the comment has that before printing the indent

**Comment by sloede** [comment]
> i think this should be fairly easy to add since in print.jl you can check if the comment has that before printing the indent

This sounds like an interesting and comparably portable approach. However, I am not sure into which function I would have to look - `print_inlinecomment` does sound correct, but it is not clear to me how and where the indent size is modified.

**Comment by domluna** [comment]
https://github.com/domluna/JuliaFormatter.jl/blob/master/src/print.jl#L49-L97

the check part is

     ws = repeat(" ", max(indent, 0))

i think adding another keyword argument would be sufficient. defaults to false and would be true if the NOTCODE node contains the string we're looking for

format: deindent

or "noindent" ?

ehh we can bikeshed that later

**Comment by domluna** [comment]
occursin(r"^#!\s*format\s*:\s*deindent\s*$", n.val) would capture it

**Comment by domluna** [comment]
I'll tackle this tonight

**Comment by sloede** [comment]
> I'll tackle this tonight

That would be fantastic, thanks a lot 🙏

FWIW, I think from a *user* perspective, `noindent` is clearer, since what the user (presumably) thinks is "I put this here to get no indentation, ie, noindent". But any keyword is fine, really.

**Comment by domluna** [comment]
@sloede this branch should do the trick https://github.com/domluna/JuliaFormatter.jl/pull/724

**Comment by domluna** [comment]
this is possible now with #724

**Comment by gdalle** [comment]
thanks!
