### ISSUE TITLE
Path separator recognized as binary operator in Markdown file

### ISSUE THREAD

**Issue by schillic** [domluna/JuliaFormatter.jl#712]
The formatter also works on Markdown files (documentation), but it does not recognize path separators correctly (and rather reads them as binary operators and adds spaces around them).

#### Before formatting

```julia
![Test](pics/a.png)
```

#### After formatting

```julia
![Test](pics / a.png)
```

**Comment by domluna** [comment]
This is probably an issue with CommonMark.jl

**Comment by schillic** [comment]
Do you mean I should ask there?

**Comment by schillic** [comment]
Actually you fixed this too in the latest release! Probably together with #714. Thanks :smiley:
