### ISSUE TITLE
invalid syntax with element-wise exponents

### ISSUE THREAD

**Issue by Alexander-Barth** [domluna/JuliaFormatter.jl#72]
JuliaFormatter is a very interesting tool that I would like to use for our projects.
However, I noticed an issue when formatting code `10 .^ logfactorsl`:

```julia
using JuliaFormatter
JuliaFormatter.format_text("10 .^ logfactorsl")
# output "10.^logfactorsl"
```

As the white-space are removed, I get the following error in Julia `invalid syntax "10.^"; add space(s) to clarify`. In my example `logfactorsl` is an array and 10 should be raised to the power of every element.

**Comment by domluna** [comment]
I guess if the LHS is a literal this is a case where we don't want to remove all the whitespace.

Thanks for reporting 👍

**Comment by Alexander-Barth** [comment]
Thanks a lot for this fix!
