### ISSUE TITLE
`import ..f` for function `f` defined in parent macro incorrectly formatted to `using ..f: f`

### ISSUE THREAD

**Issue by MilesCranmer** [domluna/JuliaFormatter.jl#723]
This is an edge case of `import`. In a child module, you can import a function `f` from the parent module with

```julia
import ..f
```

However, there is no equivalent with `using`. See https://discourse.julialang.org/t/syntax-for-import-from-parent-module/434.

Right now it seems like JuliaFormatter.jl decides to format this as

```julia
using ..f: f
```

which is incorrect, as `f` is not a module. The parent module is being referenced anonymously.

Admittedly this is an ambiguous piece of Julia syntax and I'm not sure what you could do about it.

https://github.com/JuliaLang/julia/issues/29131

**Comment by domluna** [comment]
the eternal baroque dance of import and using continues
