### ISSUE TITLE
Issues with `#! format: noindent` and comments

### ISSUE THREAD

**Issue by sloede** [domluna/JuliaFormatter.jl#728]
There seem to be some slight hiccups with the newly added (#724) `#! format: noindent` that concerns comments:

Comments not attached to a (non-indented) code entity will actually get indented. The - from what I can tell - correctly formatted snippet
```julia
begin
#! format: noindent

# This is OK
function foo end

# This is not

end
```
turns into
```julia
begin
#! format: noindent

# This is OK
function foo end

  # This is not

end
```

Even weirder, the following
```julia
begin
#! format: noindent

end
```
is turned into
```julia
begin
  #! format: noindent

end
```
Is this a feature or a bug?

**Comment by domluna** [comment]
looks like a bug to me

**Comment by sloede** [comment]
Unfortunately, I am not sure how to dig deeper on this but I'd be happy to assist with testing etc if helpful.
