### ISSUE TITLE
Add formatting test option

### ISSUE THREAD

**Issue by brunocastroibarburu94** [domluna/JuliaFormatter.jl#733]
I believe that JuliaFormatter can be used as part of the CICD pipeline of production code, we want to put a test indicating that the code submitted for a Merge Request satisfies a style guide.

Would it be possible to have a function that indicates if any file is going to be formatted and if it does it fails, or outputes the number of files that are going to be formatted without actually formatted. Ideally with links to the files and lines that may be affected by the automated formatting. 

This is similar to what package black can do in Python.

Perhaps this is already out there but I coudn't find how to use JuliaFormatter or any other tool for that matter for this.

Cheers!

**Comment by domluna** [comment]
there are some workflows already in a bunch of repos that do exactly this. Off the top of my head I think Trixi.jl folks have this setup

**Comment by domluna** [comment]
also the SciML repos have this

**Comment by brunocastroibarburu94** [comment]
Superb, for future reference in case anyone else needs it I will leave the link to [SciML workflow](https://github.com/SciML/DifferentialEquations.jl/blob/master/.github/workflows/FormatCheck.yml). Thanks @domluna!
