### ISSUE TITLE
Spacing around operators in ranges

### ISSUE THREAD

**Issue by odow** [domluna/JuliaFormatter.jl#74]
Came across this case:
```julia
julia> JuliaFormatter.format_text("0:1/3:2")
"0:1 / 3:2"

julia> 0:1 / 3:2
0.0:0.3333333333333333:2.0
```
Still parses okay, but as formatted, it's visually confusing. 

I'm not sure which option is best...
```Julia
0:1/3:2
0:(1/3):2
0:(1 / 3):2
0 : 1/3 : 2
0 : 1 / 3 : 2
```

Edit: it's also not consistent with:
```julia
julia> JuliaFormatter.format_text("0:1 / 3")
"0:1/3"
```
so maybe the best option is to remove spaces, or leave as-is in ranges.

**Comment by domluna** [comment]
It should just remove all the spaces. This is parsed as a ColonOpCall and we're not propagating nospace = true to binary calls. Should be an easy fix.

**Comment by StefanKarpinski** [comment]
I'm curious how this interacts with the recent change to leave whitespace around dotted operators? I.e. how would you format `1 : 2 .^ 3 : 123`?

**Comment by domluna** [comment]
with the most recent changes it's `"1:2 .^ 3:123"` which may or may not be ideal but otherwise we would run into the same ambiguity problem as #72
