### ISSUE TITLE
Using single quotes to create a string causes an error

### ISSUE THREAD

**Issue by jotas6** [domluna/JuliaFormatter.jl#752]
Hello! I noticed that it isn't possible to format files that try to define strings with single quotes (for example, `'Hello, world!'`). I know that this is an incorrect use of `'`, but there is some educational material where I would like to introduce this error on purpose (to make a comparison with other programming languages). 

Here is a minimal example that allows reproducing the error:

```julia
# In Julia, we define strings with "<string>"
s = "Hello, world!"

# '<string>' doesn't work
s2 = 'Hello, world!'
```

If I try to format that code, I get the following error: 

```
ERROR: Parsing error for input occurred on line 5, offset: 4
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] format_text(text::String, style::DefaultStyle, opts::JuliaFormatter.Options)
    @ JuliaFormatter ~/.julia/packages/JuliaFormatter/FF8Rk/src/JuliaFormatter.jl:684
  [3] format_text(text::String, style::DefaultStyle; kwargs::Base.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:config_applied,), Tuple{Bool}}})
    @ JuliaFormatter ~/.julia/packages/JuliaFormatter/FF8Rk/src/JuliaFormatter.jl:658
  [4] format_text
    @ ~/.julia/packages/JuliaFormatter/FF8Rk/src/JuliaFormatter.jl:655 [inlined]
  [5] #format_text#242
    @ ~/.julia/packages/JuliaFormatter/FF8Rk/src/JuliaFormatter.jl:652 [inlined]
  [6] format_text
    @ ~/.julia/packages/JuliaFormatter/FF8Rk/src/JuliaFormatter.jl:651 [inlined]
  [7] _format_file(filename::String; overwrite::Bool, verbose::Bool, format_markdown::Bool, format_options::Base.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:config_applied,), Tuple{Bool}}})
    @ JuliaFormatter ~/.julia/packages/JuliaFormatter/FF8Rk/src/JuliaFormatter.jl:777
  [8] format(path::String, options::JuliaFormatter.Configuration)
    @ JuliaFormatter ~/.julia/packages/JuliaFormatter/FF8Rk/src/JuliaFormatter.jl:922
  [9] #format#252
    @ ~/.julia/packages/JuliaFormatter/FF8Rk/src/JuliaFormatter.jl:888 [inlined]
 [10] format
    @ ~/.julia/packages/JuliaFormatter/FF8Rk/src/JuliaFormatter.jl:888 [inlined]
 [11] #format_file#247
    @ ~/.julia/packages/JuliaFormatter/FF8Rk/src/JuliaFormatter.jl:843 [inlined]
 [12] format_file(filename::String)
    @ JuliaFormatter ~/.julia/packages/JuliaFormatter/FF8Rk/src/JuliaFormatter.jl:836
 [13] top-level scope
    @ REPL[16]:1
```

I think that the error is related to the incorrect use of `'` since commenting that line out makes the error disappear. This solution has also worked for some other files where I am getting this error, all of which have this kind of example. I am not sure if this behavior is intended or if this is an issue that should be solved.

I am using `JuliaFormatter v1.0.35` and Julia `v1.9.2`.

Thanks!

**Comment by domluna** [comment]
this parsing error makes sense to me since single quotes can only be used for character literals not strings.

**Comment by domluna** [comment]
```julia
julia> CSTParser.parse("'Hello world'")
  1:13  errortoken( CSTParser.InvalidChar)
  1:13   CHAR: 'H'

julia> CSTParser.parse("'H'")
  1:3   CHAR: 'H'

julia> CSTParser.parse("'He'")
  1:4   errortoken( CSTParser.InvalidChar)
  1:4    CHAR: 'H'

julia>

julia>

julia> Meta.parse("'He'")
ERROR: ParseError:
# Error @ none:1:2
'He'
#└┘ ── character literal contains multiple characters
Stacktrace:
 [1] #parse#3
   @ Base.Meta ./meta.jl:244 [inlined]
 [2] parse
   @ Base.Meta ./meta.jl:236 [inlined]
 [3] parse(str::String; filename::String, raise::Bool, depwarn::Bool)
   @ Base.Meta ./meta.jl:278
 [4] parse(str::String)
   @ Base.Meta ./meta.jl:276
 [5] top-level scope
   @ REPL[7]:1

julia> Meta.parse("'H'")
'H': ASCII/Unicode U+0048 (category Lu: Letter, uppercase)
```

this is expected behaviour

**Comment by jotas6** [comment]
I see, I wasn't sure if this would be expected or not, so I thought it would be good to report it. Should this issue be closed now?

Thank you for taking a look.

**Comment by rben01** [comment]
Just because something doesn't parse in Julia doesn't mean it shouldn't parse in JuliaFormatter. A formatter should be more lenient so that it can format “correctly” even when what it's formatting isn't valid Julia. For instance, `a.[]` is invalid syntax, yet JuliaFormatter will correctly format around it. There are limits to how far beyond valid syntax a formatter should go, but accepting multiple characters inside single quotes sounds perfectly reasonable to me.
