### ISSUE TITLE
[SciML]: Long variable definitions turn into functions

### ISSUE THREAD

**Issue by ven-k** [domluna/JuliaFormatter.jl#753]
With SciML formatting style, `x(t) = value, [...]` turns into `function x(t)` with value as its body whenever the definition is longer than 94 chars.

MWE: 
```julia
using ModelingToolkit
@mtkmodel A begin
	@variables begin
		i(t) = 0.0, [description = "Line longer than the char limit of 94 characters", unit = u"A"]
	end
end
```

Turns into 
```julia
@mtkmodel A begin
    @variables begin
        function i(t)
            0.0,
            [description = "Line longer than the char limit of 94 characters", unit = u"A"]
        end
    end
end
```

**Comment by domluna** [comment]
is this problematic because it's not semantically the same?

**Comment by domluna** [comment]
this occurs because YASStyle has short_to_long_function_def as true and it's used quite extensively in SciMLStyle

https://github.com/domluna/JuliaFormatter.jl/blob/master/src/styles/sciml/pretty.jl#L84-L91

@YingboMa would you guys want to have different defaults than what comes with https://github.com/domluna/JuliaFormatter.jl/blob/master/src/styles/yas/pretty.jl#L24? Would it make sense to override it with the options set by SciML?

**Comment by ven-k** [comment]
> is this problematic because it's not semantically the same?

Yes. `i(t) = 0` is parsed as `i` variable dependent on `t` with default value 0.

**Comment by ChrisRackauckas** [comment]
> is this problematic because it's not semantically the same?

It's unintended in the style and not something we've wanted. I don't know how to revert it. We have disabled using the formatter until it's fixed.

**Comment by domluna** [comment]
actually the options are consistent already since they are only checked once when format_text is initially called and then saved.

this is what's causing this particular transform

```
function n_binaryopcall!(ss::SciMLStyle, fst::FST, s::State; indent::Int = -1)
    style = getstyle(ss)
    line_margin = s.line_offset + length(fst) + fst.extra_margin
    if line_margin > s.opts.margin &&
       fst.ref !== nothing &&
       CSTParser.defines_function(fst.ref[])
        transformed = short_to_long_function_def!(fst, s)
        transformed && nest!(style, fst, s)
    end

    if findfirst(n -> n.typ === PLACEHOLDER, fst.nodes) !== nothing
        n_binaryopcall!(DefaultStyle(style), fst, s; indent = indent)
        return
    end

    start_line_offset = s.line_offset
    walk(increment_line_offset!, (fst.nodes::Vector)[1:end-1], s, fst.indent)
    nest!(style, fst[end], s)
end
```

**Comment by domluna** [comment]
https://github.com/domluna/JuliaFormatter.jl/pull/754

```
using ModelingToolkit
@mtkmodel A begin
    @variables begin
        i(t) = 0.0,
        [description = "Line longer than the char limit of 94 characters", unit = u"A"]
    end
end
```

1 test fails from the change

**Comment by ChrisRackauckas** [comment]
Yes, ignoring that macro would likely be best

**Comment by domluna** [comment]
the format would be

```
@noinline require_complete(m::Matching) = m.inv_match === nothing &&
                                          throw(ArgumentError("Backwards matching not defined. `complete` the matching first."))
```

for the above example

**Comment by YingboMa** [comment]
Can we specialize on macro names in SciML style? Only ignoring `@variables` and `@parameters`'s full function transition rule.

**Comment by isaacsas** [comment]
@YingboMa do you mean special casing those macros in SciMLStyle? I’d think we would have the same issue, for example, with `@species` from Catalyst, which is just a thin wrapper around `@variables`.

**Comment by YingboMa** [comment]
Yeah, we should special case add all those macros. They don't follow Julia semantics, so we cannot transform them using the Julia semantics. Or, alternatively, we can disable function long form definition transformation all together. What do you think? @isaacsas @ChrisRackauckas

**Comment by isaacsas** [comment]
It seems like the number of such macros may only grow over time, so I’d vote to just disable it rather than having to update the style with more and more special cases.

**Comment by ChrisRackauckas** [comment]
I'd rather just opt some macros in, like `@fold`, `@muladd`, `@inbounds`, etc. rather than try and opt every single one out that would break formatting.

**Comment by YingboMa** [comment]
I would be in favor of no long form transformations at all, because I think it might be too strong to allow in a homoiconic programming language like Julia, and devs can make their own judgements on when to break a one-liner into a long form definition.

**Comment by domluna** [comment]
the problem with special casing is the formatter would only detect what's used in the file. So if you call a macro and calls another macro `@fold`, `@muladd`, etc, it would not figure out not to do the transform.
