### ISSUE TITLE
Short circuiting idiom to `if` conversion

### ISSUE THREAD

**Issue by chriselrod** [domluna/JuliaFormatter.jl#759]
It would be great if we could have an option to automatically convert
```julia
b0 && foo()
b1 || bar()
```
into
```julia
if b0
    foo()
end
if !b1
    bar()
end
```
This is a style that is often preferred for being able to tell whether a branch is taken in code coverage, so it'd be great if it can be enforced.

**Comment by domluna** [comment]
i think this would be a good option to have

**Comment by ericphanson** [comment]
xref https://github.com/domluna/JuliaFormatter.jl/issues/382
