### ISSUE TITLE
Adding trailing comma (`,`) after function parameters

### ISSUE THREAD

**Issue by singularitti** [domluna/JuliaFormatter.jl#76]
example:
```julia
julia> s = raw"""function to_qe(
           card::QPointsSpecsCard;
           indent::AbstractString = "    ",
           sep::AbstractString = " "
       )::String
           content = "$(length(card.data))\n"
           for p in card.data
               content *= indent * join([p.coordinates; p.weight], sep) * "\n"
           end
           return content
       end"""
```
after formatting:
```julia
julia> format_text(s) |> println
function to_qe(
    card::QPointsSpecsCard;
    indent::AbstractString = "    ",
    sep::AbstractString = " ",
)::String
    content = "$(length(card.data))\n"
    for p in card.data
        content *= indent * join([p.coordinates; p.weight], sep) * "\n"
    end
    return content
end
```
An extra `,` is added to `sep` parameter.
```julia
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 12

(v1.2) pkg> st
    Status `~/.julia/environments/v1.2/Project.toml`
  [98e50ef6] JuliaFormatter v0.1.11
```
Seems to be related to #44.

**Comment by domluna** [comment]
This is intentional as you can see from #44.

**Comment by singularitti** [comment]
I am not very in favor of this choice. Maybe it is OK for an iterable to have trailing commas at the end, but function parameters? It makes people feel there are still parameters. Could we have a parameter to choose whether having it or not? Would it be hard to implement? Thank you!

**Comment by StefanKarpinski** [comment]
See the reasoning in https://github.com/domluna/JuliaFormatter.jl/issues/44#issuecomment-529216121: this leads to smaller, clearer diffs and less editing required to add, remove and reorder function arguments. Go [_requires_ the trailing comma](https://stackoverflow.com/a/29354247/659248) in these situations.

**Comment by domluna** [comment]
This will remain the default but if/when we add options this would be a reasonable one to have.
