### ISSUE TITLE
Format giving wrong results

### ISSUE THREAD

**Issue by sathvikbhagavan** [domluna/JuliaFormatter.jl#769]
I have a file (test.jl) where I have this line of code:

```julia
@assert x isa Tuple "x is not a Tuple"
```

If I format it using `format("test.jl")`, I get:

```julia
@assert xisaTuple "x is not a Tuple"
```

which is wrong

Version:

```julia
[98e50ef6] JuliaFormatter v1.0.39
```

**Comment by domluna** [comment]
can you post your .JuliaFormatter.toml file with the defaults it formats fine
