### ISSUE TITLE
Request: create `pre-commit` hook

### ISSUE THREAD

**Issue by MilesCranmer** [domluna/JuliaFormatter.jl#799]
Pre-commit (https://github.com/pre-commit/pre-commit) is an extremely useful framework for managing all sorts of multi-language git hooks that apply formatting, enforce YAML formatting, check for whitespace at end of line (for any file extension), strip jupyter notebooks of plot data, etc. So when you run `git commit`, it loops through all of your various requirements before performing the commit. For example, you would have `.pre-commit-config.yml` containing:

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: [--maxkb=100]
    -   id: markdown-spellcheck
        args: [--ignore-numbers, --check-filenames, --check-hidden, --check-acronyms, --check-case, --check-urls]
        files: '\.md$'
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
    -   id: black-jupyter
-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
    -   id: nbstripout
```

I noticed that there was no JuliaFormatter hook but there are several for other languages, so I would like to put in a request for one, whenever you or someone else might have the time. There is a new hooks page here: https://pre-commit.com/#new-hooks. I think it might be possible to put it directly in this repo.

Cheers!
Miles

**Comment by hyrodium** [comment]
I'm not much familiar with pre-commit, but isn't this documentation enough?

https://domluna.github.io/JuliaFormatter.jl/dev/integrations/#pre-commit

**Comment by MilesCranmer** [comment]
Oh!! Nice! Closing... 😆

**Comment by hyrodium** [comment]
Maybe the documentation can be improved something like this:

* Move "Formatting Options" section in `index.md` to a new page in the sidebar.
* Add "How to use" section in `index.md` like this:
  * Run JuliaFormatter as an ordinary Julia package
    * Just run `using JuliaFormatter; format(".")` on your REPL
  * Use JuliaFormatter as editor extensions
    * VSCode, Emacs, Vim, Atom(deprecated) are supported.
    * On the [julia-vscode](https://github.com/julia-vscode/julia-vscode) extension, you cannot change JuliaFormatter.jl version independently of the extension version.
  * Use JuliaFormatter on pre-commit
    * See [pre-commit section](https://domluna.github.io/JuliaFormatter.jl/dev/integrations/#pre-commit) for more information.
  * Run JuliaFormatter on GitHub Actions
    * See [julia-format](https://github.com/julia-actions/julia-format) for more information.

**Comment by MilesCranmer** [comment]
Maybe? For me, it simply didn’t show up on Google. So maybe that page needs better keywords or something (or perhaps it’s not getting indexed?).

**Comment by MilesCranmer** [comment]
Although I guess this issue will now be googlable so it’s fine
