### ISSUE TITLE
Formatting of let blocks

### ISSUE THREAD

**Issue by saschatimme** [domluna/JuliaFormatter.jl#80]
I just stumbled about this

The following code (which I consider nicely formatted)
```
s = let
    tracker, starts = pathtracker_startsolutions([x^2+y^2+z^2 - 1; L₁]; system = FPSystem)
    solution(track(tracker, first(starts)))
end
```
gets formatted to

```
s =
        let
                tracker, starts = pathtracker_startsolutions(
                        [x^2 + y^2 + z^2 - 1; L₁];
                        system = FPSystem,
                )
                solution(track(tracker, first(starts)))
        end
```

**Comment by domluna** [comment]
This is intentional #27. 

Site note: Is your indentation set to 8 or is that just GH formatting?

**Comment by saschatimme** [comment]
I think GitHub messed it up.  Still think that the white spaces are somehwat excessive here, but if this is the decision made I am also fine.

**Comment by domluna** [comment]
For this example it’s a toss up but I think In the majority of cases the
latter returns a nicer output

**Comment by StefanKarpinski** [comment]
Having the `s = let` on the same line would be reasonable.
