### ISSUE TITLE
align_struct_field throws error with const keyword

### ISSUE THREAD

**Issue by maltezfaria** [domluna/JuliaFormatter.jl#802]
The following MWE errors:

```julia
txt = """
mutable struct Foo
    const a
end
"""

# line below errors unless align_struct_field is set to false, or I remove const in the struct above
format_text(txt, align_struct_field=true) 
```

Any clues why or where to look?

**Comment by domluna** [comment]
Are you on the latest version? This looks similar to bug with the const
syntax that was fixed (since const used in that setting is new)

**Comment by maltezfaria** [comment]
Thanks. I tried on both `v1.0.45` and `master`, and the error is the same.

**Comment by maltezfaria** [comment]
Thanks for the fix!
