### ISSUE TITLE
tablize chained ? : operators ?

### ISSUE THREAD

**Issue by Roger-luo** [domluna/JuliaFormatter.jl#81]
I think it is kinda common to use `? :` this way with an alignment so it looks like a table (or like a pattern matching thing), currently this formatter will break the alignment, e.g

https://github.com/QuantumBFS/YaoBlocks.jl/pull/65/files#diff-97ea3876f144984c42503714b8cd219eL14

**Comment by domluna** [comment]
I like this but it may be tricky to implement well. Perhaps https://mikeinnes.github.io/MacroTools.jl/stable/sourcewalk/ could help with this

**Comment by domluna** [comment]
this should work now with #282
