### ISSUE TITLE
SciMLStyle: space in last macro argument

### ISSUE THREAD

**Issue by daviehh** [domluna/JuliaFormatter.jl#810]
As of `JuliaFormatter v1.0.45`, gives the expected result with:

```
julia> format_text("@f(x, y, z)", SciMLStyle())
"@f(x, y, z)"
```

in versions newer than v1.0.45:
```
julia> format_text("@f(x, y, z)", SciMLStyle())
"@f(x, y,z)"
```

(the space before the last argument z is removed with the formatter, occurs only with number of arguments >= 3)

**Comment by domluna** [comment]
Strangely, the macrocall code didn't change; it might be related to
CSTParser upgrade

**Comment by daviehh** [comment]
hmm... with `CSTParser v3.4.1`, I got
```
julia> CSTParser.parse("@f(x, y, z)")
  1:11  macrocall
  1:2    @f
  3:2    NOTHING: nothing
  3:3    x
  4:4    y
  5:5    z
```

cf.
```
julia> CSTParser.parse("@f(x, y)")
  1:8   macrocall
  1:2    @f
  3:2    NOTHING: nothing
  3:3    x
  4:4    y
```

looks about right?

**Comment by domluna** [comment]
I got a fix coming in.

**Comment by daviehh** [comment]
thanks for the quick fix!
