### ISSUE TITLE
Boolean conditions don't break

### ISSUE THREAD

**Issue by saschatimme** [domluna/JuliaFormatter.jl#87]
This code

```julia
function isdone(solutions::UniquePoints, x, options::MonodromyOptions)
    options.done_callback(x, solutions.points) || length(solutions) ≥ options.target_solutions_count
end
```

stays the same after formatting, although it runs over the maximal line length.
A good result would probably be

```julia
function isdone(solutions::UniquePoints, x, options::MonodromyOptions)
    options.done_callback(x, solutions.points) ||
    length(solutions) ≥ options.target_solutions_count
end
```

**Comment by domluna** [comment]
The heuristics for breaking lazy ops are a bit outdated and I need to revisit them. At the moment it doesn't break on just 2 arguments, `arg1 || arg2`, unless it's part of an if statement or while loop condition.

**Comment by StefanKarpinski** [comment]
I would modify the expected output to indent the second line, ie:
```jl
function isdone(solutions::UniquePoints, x, options::MonodromyOptions)
    options.done_callback(x, solutions.points) ||
        length(solutions) ≥ options.target_solutions_count
end
```

**Comment by mlubin** [comment]
:+1:. I ran JuliaFormatter and had lines with boolean conditions re-formatted to no longer respect the margins.

**Comment by domluna** [comment]
Gonna close this since I got rid of the heuristic I had before.
