### ISSUE TITLE
New formatting turns optional positional argument into keyword argument

### ISSUE THREAD

**Issue by gdalle** [domluna/JuliaFormatter.jl#878]
Kudos on the full rewrite!
Unfortunately I have encountered a bug when I tried to apply the new formatting in https://github.com/gdalle/DifferentiationInterface.jl/pull/589. An unnamed, `Val`-typed positional argument was "formatted" into a keyword argument (see [this comment](https://github.com/gdalle/DifferentiationInterface.jl/pull/589/files#r1803531574)).

Schematically, the following code
```julia
function f(x, y, ::Val{N}=Val(1)) where {N}
```
turned into (note the semicolon)
```julia
function f(x, y; (::Val{N})=Val(1)) where {N}
```
which changed the semantics.

EDIT: As discussed below, this apparently applied to all _optional_ positional arguments, named or not. It might be due to BlueStyle.

**Comment by MilesCranmer** [comment]
Same bug unfortunately. All optional arguments (named or not) seem to get converted to keyword arguments.

@domluna do you think you could yank versions 2.0.0 and 1.0.62 until these bugs and #879 are patched? (I am unfortunately needing to patch all my CI scripts at the moment).

Thanks for all your hard work!!

**Comment by domluna** [comment]
> 
> @domluna do you think you could yank versions 2.0.0 and 1.0.62 until these bugs and #879 are patched? (I am unfortunately needing to patch all my CI scripts at the moment).

what do I need to do to yank the release?

**Comment by avik-pal** [comment]
https://github.com/JuliaRegistries/General#when-is-yanking-a-release-appropriate open a PR with `yanked=true`

**Comment by domluna** [comment]
@MilesCranmer why does 1.0.62 need to be yanked?

**Comment by MilesCranmer** [comment]
The latest version of 1 seemed to change the rules in a breaking way, not sure the number

**Comment by domluna** [comment]
> 
The latest version of 1 seemed to change the rules in a breaking way, not sure the number

there hasn't been any major changes for the past few releases, is there an example?

**Comment by gdalle** [comment]
Here's a minimum working example:

```julia
julia> using JuliaFormatter  # version 2

julia> format_text("""
       function f(::Vector{T}) where {T}
           return nothing
       end
       """, BlueStyle()) |> println
function f(::Vector{T}) where {T}
    return nothing
end

julia> format_text("""
       function f(::Vector{T}=[]) where {T}
           return nothing
       end
       """, BlueStyle()) |> println
function f(; (::Vector{T})=[]) where {T}
    return nothing
end
```

**Comment by MilesCranmer** [comment]
@domluna I see, then that’s probably my mistake, and it’s only 2.0.0 that should be yanked. 

(What I assume happened is I added 1.0.62 to my env, but 2.0.0 was already loaded somewhere from my base env, and that’s what actually did the formatting. I’ll double check this though.)
