### ISSUE TITLE
Skipping lines within a file

### ISSUE THREAD

**Issue by odow** [domluna/JuliaFormatter.jl#91]
So we have the `# nofmt` header, but there are a few cases where I want to exclude some lines from the formatter, e.g.,"
```Julia
... code I want formatted ...

# JuliaFormatter: off
data = [ ... very long line I don't want wrapped ... ]
# JuliaFormatter: on

... code I want formatted ...
```

The idea is that the `# JuliaFormatter: XXX` directives are file-local, so we should replace the `# nofmt` header with `# JuliaFormatter: off`, and this would be equivalent to excluding every line in the file.

**Comment by StefanKarpinski** [comment]
Might be good to use syntax that's slightly less likely to be used accidentally, maybe
```
#! JuliaFormatter: [off|on]
```

**Comment by domluna** [comment]
Makes sense. I think the implementation could be straightforward enough, probably build from `Notcode` in some way.
